### ISSUE TITLE
support cloudflare_certificate_pack data

### ISSUE THREAD

**Issue by mbelang** [cloudflare/terraform-provider-cloudflare#1052]
### Current Terraform and Cloudflare provider version

terraform -v
Terraform v0.14.10
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/aws v3.38.0

### Description

Having cloudflare_certificate_pack data would be useful to retrieve information like the certificate txt value in order to use to in other resources to automatically create the validation txt record.

### Use cases

We want to get the certificate pack txt value in order to automatically create the associated txt record to allow validation of the cert pack.

### Potential Terraform configuration

```hcl
resource "cloudflare_zone" "example" {
    zone = "example.com"
}

resource "cloudflare_certificate_pack" "example" {
  zone_id               = cloudflare_zone.example.id
  type                  = "advanced"
  hosts                 = ["example.com", "*.example.com"]
  validation_method     = "txt"
  certificate_authority = "digicert"
}

data "cloudflare_certificate_pack" "example" {
  zone_id = cloudflare_zone.example.id
  cert_pack_id = cloudflare_certificate_pack.example.id
}
...
```

### References

The certificate txt value is available in the api v4 Get Certificate Pack response:

```json
{
  "result": {
    "id": "<redacted>",
    "type": "advanced",
    "hosts": [
      "*.example.com",
      "example.com"
    ],
    "primary_certificate": 0,
    "status": "pending_validation",
    "certificates": [],
    "created_on": "2021-05-05T13:00:15.714111Z",
    "validity_days": 90,
    "validation_method": "txt",
    "validation_records": [
      {
        "txt_name": "example.com",
        "txt_value": "ca3-<redacted>"
      }
    ],
    "certificate_authority": "digicert"
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

**Comment by jacobbednarz** [comment]
is there a reason why you've opted for a new data source over exposing these on the resource itself? i agree with the concept but not sure why we'd need this separate if you're already managing the certificate in Terraform.

**Comment by mbelang** [comment]
The cert_pack_resource doesn't provide the the output that I want because the API itself doesn't return that value on creation of the certificate. Only get cert pack returns the value that I want.

**Comment by jacobbednarz** [comment]
When a resource is created, internally it also calls the `Read` method which is the `GetCertificatePack` endpoint in order to sync the state. As that is the case, I'm 👍 to adding this to the existing resource instead of a new data source. 

Do you want to submit a PR for this one?

**Comment by komljen** [comment]
I think the ability to read `validation_records` from the existing `cloudflare_certificate_pack` would be enough to automate the process of adding txt records automatically.

**Comment by crisp2u** [comment]
Any updates on this ? Kinda defeats the purpose of the `cloudflare_certificate_pack` resource if we cannot automatically validate the certificate via the TXT record

**Comment by garrettgalow** [comment]
This got fixed recently but we need to update the docs before we call this closed - https://github.com/cloudflare/terraform-provider-cloudflare/blob/332bf001d606db2dd49a4118ca10efd3672744a7/cloudflare/schema_cloudflare_certificate_pack.go#L49

**Comment by danielmotaleite** [comment]
+1 here

I'm creating several cloudflare_certificate_pack for different domains using this module:

```
variable "zone_id" {}
variable "wildcards" {}

# Advanced certificate manager for DigiCert
resource "cloudflare_certificate_pack" "advanced_digicert" {
  zone_id               = var.zone_id
  type                  = "advanced"
  hosts                 = var.wildcards
  validation_method     = "txt"
  validity_days         = 365
  certificate_authority = "digicert"
  cloudflare_branding   = false

  #wait_for_active_status = true

  lifecycle {
    create_before_destroy = true
  }
}

output "validation-txt" {
  description = "txt data to validade certificate"
  value = cloudflare_certificate_pack.advanced_digicert.validation_records == null ? "unknown" : coalesce(cloudflare_certificate_pack.advanced_digicert.validation_records[0].txt_value, "unknown" )
}
```
And then i call the module and update the route53 Domain main TXT  record using the validation-txt output.
All looks perfect, but when i run this the first time,  cloudflare_certificate_pack.advanced_digicert.validation_records  is null (that is exactly why i have the above code to test null) and the TXT record is created with "unknown"

I have to run a second apply, so the cloudflare_certificate_pack.advanced_digicert.validation_records  do have the correct values and finally the TXT is corrected

Finally,looks like after the certificate is active, the validation record gets emptied, so i need the coalesce to avoid later errors of empty string

Am i missing something, or is this a bug? i would say that the provider should wait for the validation info, so the output is correctly set without requiring running apply twice. The disappearing validation data, is weird, but not so much critical

**Comment by komljen** [comment]
I might be wrong, but at least in my case when I switched from letsencrypt to digicert, I don't have to add validation records anymore. I still have a `cloudflare-verify` validation record for cloudflare zone, so I guess that is enough for this certificate to get validated. 

Maybe `validation_records` is `null` only when using digicert?

**Comment by danielmotaleite** [comment]
If you use cloudflare as DNS provider, it should automatically create the validation record, if i recall correctly from the documentation. In my case, i'm using route53, so that do not work

**Comment by komljen** [comment]
I'm using [partial DNS](https://developers.cloudflare.com/dns/zone-setups/partial-setup/), and route53 is my primary DNS provider.

**Comment by danielmotaleite** [comment]
@komljen are you using wildcards or plain FQDN certificates? FQDN can use http validation, while wildcard certificates do require email or txt validation

**Comment by komljen** [comment]
I use wildcard certs. Basically, I can go to the CF web console and create a new DigiCert wildcard cert, which gets validated immediately without needing to add a validation record in route53. The important part is that this only works with DigiCert and not lets-encrypt.

The only record that I have is zone validation. Here is a TF code for that:
```
resource "aws_route53_record" "cloudflare_verify" {
  name    = "cloudflare-verify.${module.common_local_vars.env._root_domain}"
  ttl     = 300
  type    = "TXT"
  zone_id = data.aws_route53_zone.main.zone_id

  records = [
    cloudflare_zone.main.verification_key
  ]
}
```

**Comment by danielmotaleite** [comment]
ok, it is strange... maybe it is not really being verified! :D 
i will try and check if the TXT is really required or not them :)
thanks for the help

**Comment by danielmotaleite** [comment]
![image](https://user-images.githubusercontent.com/11890049/194444752-3e38261f-d675-4cc4-98d6-31139cfbfbe7.png)
nope, didn't worked for me in a domain that never had a certificate ... but maybe it works in domain that already had a CF certificate and digicert do some validation cache when the request arrives from the same CF account that was validated before

**Comment by danielmotaleite** [comment]
![image](https://user-images.githubusercontent.com/11890049/194445072-b9423f75-5ad4-4e6d-9b79-bad076f687e4.png)

nope, didn't worked for me in a domain that never had a certificate ... but maybe it works in domain that already had a CF certificate and digicert do some validation cache when the request arrives from the same CF account that was validated before

**Comment by evanrappe** [comment]
Any updates on how this is _supposed_ to work? I tried creating a `google` cert as we're trying to plan for the upcoming Digicert deprecation, and as @danielmotaleite demonstrated, the validation records don't appear in the state until the second apply. (I simply created a `certificate_pack` resource and piped the `validation_records` to an output. 

Is the issue that the `GetCertPack` call to sync the state happens before the actual apply to create the cert? Would it make sense to sync the state again in the apply logic before finalizing the state?

**Comment by bluemalkin** [comment]
Yes this would be really handy please !

**Comment by sigmaris** [comment]
Using Cloudflare provider v4.17.0 it still requires two runs of `apply` to get the `validation_records` data, this is very counter-intuitive as a resource that creates something normally outputs useful details on the thing after it's been created.

Contrast with, for example, `aws_acm_certificate` which outputs the required domain validation records which can immediately be [used to create DNS records, and validate the certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation), all in one run of Terraform `apply`.

**Comment by jedupuis** [comment]
Any update please ? Same problem for me using provider v4.21

**Comment by kwcrook** [comment]
The DCV delegation URL seems to be static for Cloudflare zones. Storing the DCV record somewhere and using it to build the CNAME target for TXT validation could work as a workaround:
```
resource "cloudflare_certificate_pack" "auth_certificate" {
  validation_method     = "txt"
  . . . 
}

locals {
  cloudflare_zones = {
    "myzone": "1234567890.dcv.cloudflare.com",
    "myotherzone": "a1234567890.dev.cloudflare.com"
  }
}

resource "your_dns_provider" "cert_validation" {
  . . . 
  name     = "_acme-challenge.${var.host}"
  type     = "CNAME"
  records  = ["${var.host}.${local.dcv_delegation[var.zone_name]}"]
}
```

**Comment by danielmotaleite** [comment]
yes, using a TFvar or a local for storing the DVC record do work, but i have around 50 domains, just manually gathering the list to add to a local var is a major pain

i quickly created this script, to use the cloudflare api and get in the output the domain name and the dvc, ready to copy&paste to a tfvar

Export the CLOUDFLARE_EMAIL, CLOUDFLARE_TOKEN and your CLOUDFLARE_ACCOUNT and have fun
if you have more than 50 domains, increment the page=1 until you get all the domains
```
 curl -s --request GET      --header 'Content-Type: application/json'   -H "X-Auth-Email: ${CLOUDFLARE_EMAIL}" -H "X-Auth-Key: ${CLOUDFLARE_TOKEN}" --url   "https://api.cloudflare.com/client/v4/zones?per_page=50&page=1&account.id=${CLOUDFLARE_ACCOUNT}"  | \
  jq '.result[] | (.name,.id) ' | \
  sed 'N; s/\n/ /g; s/"//g'  | \
  awk '{ print "echo \\\""$1"\\\""; print "curl --request GET      --header \"Content-Type: application/json\"   -H \"X-Auth-Email: ${CLOUDFLARE_EMAIL}\"
 -H \"X-Auth-Key: ${CLOUDFLARE_TOKEN}\" --url https://api.cloudflare.com/client/v4/zones/"$2"/dcv_delegation/uuid    -s | jq \".result.uuid\" "}' | \
  bash  | \
  sed 'N; s/\n/ = /g; s/^/  /g; s/"$/.dcv.cloudflare.com"/g'
```

yes, it is a bash script, so quick and dirty, as it should  ;)
bash, curl, sed, awk and jq required, but you can replace bash with your preferred shell

and yes, the cloudflare provider should add this to a data source, so we don't need to manage manual tfvar

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
