### ISSUE TITLE
V5 `cloudflare_api_token`s value is constantly delete

### ISSUE THREAD

**Issue by tete17** [cloudflare/terraform-provider-cloudflare#5045]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.10.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v5.0.0
+ provider registry.terraform.io/hashicorp/vault v4.6.0

### Affected resource(s)

 * `cloudflare_api_token`

### Terraform configuration files

```hcl
resource "cloudflare_api_token" "cloudflare_exporter" {
  name = "cloudflare-exporter"
  policies = [{
    effect = "allow"
    permission_groups = [
      { id = "4ec32dfcb35641c5bb32d5ef1ab963b4" },
      { id = "9c88f9c5bce24ce7af9a958ba9c504db" },
      { id = "b89a480218d04ceb98b4fe57ca29dc1f" },
      { id = "c1fde68c7bcc44588cbb6ddbc16d6480" },
      { id = "fb39996ee9044d2a8725921e02744b39" },
      //{ id = data.cloudflare_api_token_permissions_groups_list.all.result["Analytics Read"], },
      //{ id = data.cloudflare_api_token_permissions_groups_list.all.result["Account Analytics Read"], },
      //{ id = data.cloudflare_api_token_permissions_groups_list.all.result["Account Settings Read"], },
      //{ id = data.cloudflare_api_token_permissions_groups_list.all.result["Firewall Services Read"], },
      //{ id = data.cloudflare_api_token_permissions_groups_list.all.result["Account Rulesets Read"], },
    ]
    resources = {
      for zone in data.cloudflare_zone.allowed_zones :
      "com.cloudflare.api.account.zone.${zone.zone_id}" => "*"
    }
    }
  ]
}

resource "vault_generic_secret" "prometheus-cloudflare" {
  path = "REDACTED/prometheus-cloudflare/cloudflare"
  data_json = jsonencode({
    token : cloudflare_api_token.cloudflare_exporter.value
    zones : join(",", [for zone in data.cloudflare_zone.allowed_zones : zone.zone_id])
  })
}
```

### Link to debug output

https://gist.github.com/tete17/848dd78a9a99ba0aaf19d8309ebd9c97

### Expected output

A ver common pattern in our terraform workspaces is to automatically generate secrets like tokens or credentials through terraform and automatically inject them into our secret store for our systems to use.

We understand it means the credentials are stored in the state but we heavily control the access to the state file and we like the quick and easy management of renewal this way,

We understand that for security reasons cloudflare would never return the token value after the initial key creation but we like the value to be persisted in the state after the first run like we did for the 4.X branch.

We expect that tokens created with the provider keep the `value` field populated with the credential.

### Actual output

Instead what we see is that the `value` field is immediately wiped out of existence after the inmediat `terraform apply`

We suspect it is because after the re-implementation the provider blindly sets the terraform state as a raw version of the api response without considering anything else. This combined with the fact cloudflare returns `null` in the token value after the initial get api call leads to this effect of wiping the credential on the second run.

### Steps to reproduce

1. Write a small `cloudflare_api_token` with a random set of permissions
2. Run `terraform apply`
3. Check the state and see that the `value` key is indeed populated and can be used to inject into other resources
4. Run `terraform plan`
5. You should see a change in the resource mentioning the removal of the `value` field as terraform api returned null and the provider blindly set that as the resource state.  

### Additional factoids

Obviously this is an aftermath of the v5 rewrite.

**Comment by jacobbednarz** [comment]
please provide the debug logs for this to be triaged.

**Comment by tete17** [comment]
Hi @jacobbednarz thanks for the quick replay.

I will try to get you the logs with a minimal terraform project with just one resource.

Did you manage to reproduce it using the steps I mentioned above?

**Comment by jacobbednarz** [comment]
the following example works for me and keeps the values.

```hcl
resource "cloudflare_api_token" "example-repro" {
  name = "example-repro"

  policies = [{
		effect = "allow"
		permission_groups = [{
		  id = "82e64a83756745bbbb1c9c2701bf816b" # DNS read
		}]
		resources = {
		  "com.cloudflare.api.account.zone.*" = "*"
		}
  }]
}
```

unless i can get some debug logs here to demonstrate what is happening, there isn't a whole lot more i can do.

**Comment by davidharkis** [comment]
This can be easily replicated

resource "cloudflare_api_token" "token" {
  name = "test-token"
  policies = [{
    effect = "allow"
    permission_groups = [{
      id = "82e64a83756745bbbb1c9c2701bf816b"   # DNS Read
    }]
    resources = {
      "com.cloudflare.api.account.zone.*" = "*"
    }
  }]
}

output "value" {
  sensitive = true
  value = sha256(cloudflare_api_token.token.value)
}


1. Run terraform apply
2. Run terraform plan

`Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid function argument
│ 
│   on main.tf line 16, in output "value":
│   16:   value = sha256(cloudflare_api_token.token.value)
│     ├────────────────
│     │ while calling sha256(str)
│     │ cloudflare_api_token.token.value is null
│ 
│ Invalid value for "str" parameter: argument must not be null.
╵`

[terraform.log](https://github.com/user-attachments/files/18784082/terraform.log)

**Comment by jacobbednarz** [comment]
thanks. this has been fixed by #5171 and will be available in the next release. if you'd like this immediately, you can build a local version based on the `next` branch.

**Comment by boillodmanuel** [comment]
Hi @jacobbednarz ,

Do you plan to release a new version soon, even a bug fix version (5.1.1)?

I'm currently migrating from provider 4 to provider 5, and this is far from easy. This is the last bug I got, but I cannot finalize the migration until this is released.
Regards,

Manuel

**Comment by zuozp8** [comment]
> Do you plan to release a new version soon, even a bug fix version (5.1.1)?

I think they release every 2 week, so there should be release this week

**Comment by boillodmanuel** [comment]
Hi @jacobbednarz ,

Do you plan to release a new version soon, even a bug fix version (5.1.1)?

Regards

**Comment by khawarizmus** [comment]
@jacobbednarz I am facing the same issue and it's a blocker

**Comment by khawarizmus** [comment]
Hello @jacobbednarz 

Could you please provide a clear expectation of when the fix is released? #5138 

This is a critical bug since there is no way to get the value out and it's a clear blocker for people who rely on this provider to create tokens.

Also using the provider locally doesn't help in my case as i need to pass the output around, for different CD/CI pipelines.

There are already few issues related to this bug and few people are already asking the same question
cc: @boillodmanuel @saurabh2590

**Comment by davidharkis** [comment]
> Hello [@jacobbednarz](https://github.com/jacobbednarz)
> 
> Could you please provide a clear expectation of when the fix is released? [#5138](https://github.com/cloudflare/terraform-provider-cloudflare/pull/5138)
> 
> This is a critical bug since there is no way to get the value out and it's a clear blocker for people who rely on this provider to create tokens.
> 
> Also using the provider locally doesn't help in my case as i need to pass the output around, for different CD/CI pipelines.
> 
> There are already few issues related to this bug and few people are already asking the same question cc: [@boillodmanuel](https://github.com/boillodmanuel) [@saurabh2590](https://github.com/saurabh2590) [@davidharkis](https://github.com/davidharkis) [@lavaturtle](https://github.com/lavaturtle)

Yes this a direct blocker for us too. I don't recall the last time there was such a significant gap between releases.

I would just use v4, but Cloudflare have decided to not support certain product features that we need, forcing the upgrade to v5, such as setting a jurisdiction on R2 buckets.

**Comment by dduportal** [comment]
Same here, this is blocking us on the Jenkins project to upgrade. R2 credential rotation is mandatory once you've started the migration.

Worth notes in the migration notes to let users know they should wait 1 or 2 more releases before trying migration.

**Comment by AlessioCasco** [comment]
I have updated the provider to `v5.2.0` but I still see the issue.

Terraform, for resource `cloudflare_api_token` shows this along with a ton of other changes in the resource:
```terraform
[...]
      + value        = (sensitive value)
[...]
```

It tricked me, I was hoping that we finally had the token, but unfortunately, it seems we are back to square one, where no token is saved in the state or have the ability to fetch it when called with `cloudflare_api_token.something.value.

**Comment by mfadmitrenko** [comment]
Hi, 

The issue is not fixed, please reopen it. Providers are the following - 

`   vault = {
      source  = "hashicorp/vault"
      version = "~> 4.7.0"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.2"
    }`

And if you try to access value it is still Null. When I did target apply for 1 test token the value that ended up in Vault was Null. 

You can also reproduce the problem as it was mentioned above i.e

`terraform console
> cloudflare_api_token.api_token["<redacted>"]
{
  "condition" = null /* object */
  "expires_on" = tostring(null)
  "id" = "<redacted>"
  "issued_on" = "2025-01-22T16:08:32Z"
  "last_used_on" = tostring(null)
  "modified_on" = "2025-01-22T16:08:33Z"
  "name" = "<redacted>"
  "not_before" = tostring(null)
  "policies" = tolist([
    {
      "effect" = "allow"
      "id" = "<redacted>"
      "permission_groups" = tolist([
        {
          "id" = "82e64a83756745bbbb1c9c2701bf816b"
          "meta" = null /* object */
          "name" = "DNS Read"
        },
      ])
      "resources" = tomap({
        "com.cloudflare.api.account.zone.<redacted>" = "*"
      })
    },
  ])
  "status" = "active"
  "value" = (sensitive value)
}
> cloudflare_api_token.api_token["<redacted>"].value
(sensitive value)
> sha256(cloudflare_api_token.api_token["<redacted>"].value)
╷
│ Error: Invalid function argument
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ Invalid value for "str" parameter: argument must not be null.
╵
`

**Comment by boillodmanuel** [comment]
I'm not sure that cloudflare team (including @jacobbednarz) is notified when we comment a closed issue. It may worth to open a new issue

**Comment by ritaCanavarro** [comment]
@boillodmanuel I created an issue similar to this one as we are still suffering from it :( 

New issue can be found here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/5648

**Comment by boillodmanuel** [comment]
Thanks @ritaCanavarro  👍
