### ISSUE TITLE
cloudflare_zero_trust_gateway_policy rule_settings keeps changing

### ISSUE THREAD

**Issue by Kiblyn11** [cloudflare/terraform-provider-cloudflare#5394]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

cloudflare_zero_trust_gateway_policy  rule_settings keeps changing
Applying does not solve the issue, and it is bound to happen on next apply

### Affected resource(s)

cloudflare_zero_trust_gateway_policy 

### Terraform configuration files

```hcl
resource "cloudflare_zero_trust_gateway_policy" "my_rule" {
  account_id     = "..."
  enabled        = true
  name           = "My rule"
  precedence     = 3
  action         = "allow"
  filters        = ["l4"]
  traffic        = "net.dst.ip in {0.0.0.0/0}"
  rule_settings = {
    check_session = {
      duration = "24h0m0s"
      enforce  = true
    }
  }
}
```

### Link to debug output

N/A

### Expected output

No diff on subsequent apply

### Actual output

  # module.cloudflare_ztna.cloudflare_zero_trust_gateway_policy.my_rule will be updated in-place
  ~ resource "cloudflare_zero_trust_gateway_policy" "my_rule" {
      ~ created_at     = "2024-05-31T13:26:25Z" -> (known after apply)
      + deleted_at     = (known after apply)
      + expiration     = (known after apply)
        id             = "..."
        name           = "..."
      ~ rule_settings  = {
          + audit_ssh                          = (known after apply)
          + biso_admin_controls                = (known after apply)
          - block_page_enabled                 = false -> null
          - block_reason                       = "" -> null
          + dns_resolvers                      = (known after apply)
          + egress                             = (known after apply)
          - insecure_disable_dnssec_validation = false -> null
          - ip_categories                      = false -> null
          - ip_indicator_feeds                 = false -> null
          + l4override                         = (known after apply)
          + notification_settings              = (known after apply)
          - override_host                      = "" -> null
          + payload_log                        = (known after apply)
          + quarantine                         = (known after apply)
          + resolve_dns_internally             = (known after apply)
          + untrusted_cert                     = (known after apply)
            # (1 unchanged attribute hidden)
        }
      + schedule       = (known after apply)
      ~ updated_at     = "..." -> (known after apply)
      ~ version        = 1 -> (known after apply)
        # (9 unchanged attributes hidden)
    }

### Steps to reproduce

Apply cloudflare_zero_trust_gateway_policy

**Comment by jacobbednarz** [comment]
please provide the versions and TF_LOG=DEBUG output for this one to be triaged.

**Comment by krknopp** [comment]
try provider version 5.1.0.  I think this looks like the same issue we're seeing in #5419

**Comment by vaishakdinesh** [comment]
We've got a working reproduction and did a root cause analysis. We created an internal ticket for the team responsible for API. Thank you!
cc: @jhutchings1

**Comment by rexscaria** [comment]
We have recently fixed the issue of identity, rule_settings and device_posture being confused between null and empty string. This will be available at soon releasing 5.4.0
For the rule settings that are marked as null in the tf files plan apply cycle, you may give default values for now, this should fix 
Like in your policy TF file, you could explicitly write

{
   identity = ""
   rule_settings = {  block_page_enabled = false }
}

this will fix the issue for now. But in 5.4.0 this will be automatically handled.
Thanks for reporting.

**Comment by renanvizza-prontmed** [comment]
Still happpening, for every plan or apply. 5.4.0

ignore does not work...
```hcl
lifecycle {
    ignore_changes = [rule_settings]
  }
```

.terraform.lock.hcl
```hcl
provider "registry.terraform.io/cloudflare/cloudflare" {
  version     = "5.4.0"
  constraints = "~> 5.0"
  hashes = [
    "h1:Rs5gaiRip5QqC3cV6BhTtvfAvOILxTmY40Ktty3DeYY=",
    "zh:08b35ad7c1125bd0f34a0e719231389a679dc4a0247aa7c46374a55f13658a5a",
    "zh:10c68c3a847b22c85db45d401febb9b34e0c0dadc38c4cc8f22b031cc9ff53de",
    "zh:1750f58bd37db19f1d92a4232db359505993f1e2d8ba7d6732b1b59f098da902",
    "zh:3929072b8dab83cc630d18a2ec04b339342d6dea7da7f51b733ffbd2543177b8",
    "zh:9b297eeb027cd7e01f392d94a408070dcb801f09bf58a60a1a7f356bd78b40f5",
    "zh:9d90bd226699737d00532927491e7ae0c30a5df407d39d0a29fa0bb2eedb5a7e",
    "zh:a3b28a5e0114488b50ef0887e3fb8f8baa74058d1b33a57b1c8917e5be954ef1",
    "zh:afd7388049fdbe3b0c21f3141ad623c970ab6c341c8fbab91041dc665c4331f7",
    "zh:f809ab383cca0a5f83072981c64208cbd7fa67e986a86ee02dd2c82333221e32",
  ]
}
```

main.tf
```hcl
resource "cloudflare_zero_trust_gateway_policy" "bypass_cert_check" {
  depends_on = [azurerm_kubernetes_cluster.cluster]
  account_id = module.shared.cloudflare_account_id
  name       = "aks-domain-no-check"
  enabled    = true
  traffic    = "any(http.conn.domains[*] in {\"${azurerm_kubernetes_cluster.cluster.private_fqdn}\"})"
  action     = "off"
  filters    = ["http"]
  precedence = 688
  identity   = ""


  rule_settings = {
    ignore_cname_category_matches      = false
    insecure_disable_dnssec_validation = false
    resolve_dns_through_cloudflare     = false
    block_page_enabled                 = false
    ip_categories                      = false
    ip_indicator_feeds                 = false
  }
}
```

plan.json
```json
{
  "address": "cloudflare_zero_trust_gateway_policy.bypass_cert_check",
  "mode": "managed",
  "type": "cloudflare_zero_trust_gateway_policy",
  "name": "bypass_cert_check",
  "provider_name": "registry.terraform.io/cloudflare/cloudflare",
  "change": {
    "actions": [
      "update"
    ],
    "before": {
      "account_id": "<REDACTED>",
      "action": "off",
      "created_at": "2025-05-09T02:36:20Z",
      "deleted_at": null,
      "description": "",
      "device_posture": "",
      "enabled": true,
      "expiration": null,
      "filters": [
        "http"
      ],
      "id": "5cbe9379-1369-4242-98cb-072e29d92b94",
      "identity": "",
      "name": "aks-domain-no-check",
      "precedence": 688,
      "rule_settings": {
        "add_headers": null,
        "allow_child_bypass": null,
        "audit_ssh": null,
        "biso_admin_controls": null,
        "block_page": null,
        "block_page_enabled": false,
        "block_reason": "",
        "bypass_parent_rule": null,
        "check_session": null,
        "dns_resolvers": null,
        "egress": null,
        "ignore_cname_category_matches": null,
        "insecure_disable_dnssec_validation": false,
        "ip_categories": false,
        "ip_indicator_feeds": false,
        "l4override": null,
        "notification_settings": null,
        "override_host": "",
        "override_ips": null,
        "payload_log": null,
        "quarantine": null,
        "redirect": null,
        "resolve_dns_internally": null,
        "resolve_dns_through_cloudflare": null,
        "untrusted_cert": null
      },
      "schedule": null,
      "traffic": "any(http.conn.domains[*] in {\"mydomain\"})",
      "updated_at": "2025-05-10T00:33:05Z",
      "version": 1
    },
    "after": {
      "account_id": "<REDACTED>",
      "action": "off",
      "description": "",
      "device_posture": "",
      "enabled": true,
      "filters": [
        "http"
      ],
      "id": "5cbe9379-1369-4242-98cb-072e29d92b94",
      "identity": "",
      "name": "aks-domain-no-check",
      "precedence": 688,
      "rule_settings": {
        "add_headers": null,
        "allow_child_bypass": null,
        "block_page_enabled": false,
        "block_reason": "",
        "bypass_parent_rule": null,
        "dns_resolvers": null,
        "egress": null,
        "ignore_cname_category_matches": false,
        "insecure_disable_dnssec_validation": false,
        "ip_categories": false,
        "ip_indicator_feeds": false,
        "l4override": null,
        "override_host": "",
        "override_ips": null,
        "quarantine": null,
        "resolve_dns_through_cloudflare": false,
        "untrusted_cert": null
      },
      "schedule": null,
      "traffic": "any(http.conn.domains[*] in {\"mydomain\"})"
    },
    "after_unknown": {
      "created_at": true,
      "deleted_at": true,
      "expiration": true,
      "filters": [
        false
      ],
      "rule_settings": {
        "audit_ssh": true,
        "biso_admin_controls": true,
        "block_page": true,
        "check_session": true,
        "notification_settings": true,
        "payload_log": true,
        "redirect": true,
        "resolve_dns_internally": true
      },
      "updated_at": true,
      "version": true
    },
    "before_sensitive": {
      "filters": [
        false
      ],
      "rule_settings": {}
    },
    "after_sensitive": {
      "expiration": {},
      "filters": [
        false
      ],
      "rule_settings": {
        "audit_ssh": {},
        "biso_admin_controls": {},
        "block_page": {},
        "check_session": {},
        "notification_settings": {},
        "payload_log": {},
        "redirect": {},
        "resolve_dns_internally": {}
      }
    }
  }
}
```

**Comment by ktaf** [comment]
We're experiencing the same issue on provider 5.4.0 on every plan/apply.

**Comment by rexscaria** [comment]
we have been squashing these bugs one by one. And finally cleared this minefield. We needed the schema to be `computed: false`, in order to accommodate the unset settings being null and not present in the api response.

This is now fixed and expect to work in the next version 5.5.0

**Comment by rexscaria** [comment]
@Kiblyn11  Can you share the snippet of setting that is getting caught in the loop?

i can not reproduce this anymore at v5.5.0

**Comment by rexscaria** [comment]
I believe that `biso_admin_controls = null` should solve that. I couldn't reproduce it. But i think it is the bare minimum settings we return in the api. So terraform is forcing us to have that in the file.

**Comment by golgoth31** [comment]
Hi, thank you for your answer.
Unfortunately, no, the resource is still complaining about `biso_admin_controls` even if null in the resource definition

**Comment by rexscaria** [comment]
So here is how it is setup.

the rule settings  always should have following values set to something. This is bacause these fields are always returned in API response even when unset.

```
block_page_enabled = false
block_reason = ""
insecure_disable_dnssec_validation = false
ip_categories = false
ip_indicator_feeds = false
override_host = ""
biso_admin_controls = null
```

Can you try a `terraform refresh` to see if the TF files have drifted from the real API? If this still haven't resolved by that. I might need to see the whole problematic resource in TF, with sensitive items masked with some regular values?

Also running `TF_PROVIDER_LOG=1 TF_LOG=DEBUG terraform plan` would give you more info on why exactly `biso_admin_controls` needed to change.

**Comment by ILLISIS** [comment]
Same issue on both a freshly imported and freshly created resource.

I tried to get the above but I have an insanely long debug due to my other resources.

**Comment by Kiblyn11** [comment]
Still have the issue on 5.6.0.
biso_admin_controls always changing even with `biso_admin_controls = null`

```
... [DEBUG] provider.terraform-provider-cloudflare_v5.6.0: marking computed attribute that is null in the config as unknown: @module=sdk.framework tf_attribute_path="AttributeName(\"rule_settings\").AttributeName(\"biso_admin_controls\")" tf_provider_addr=registry.terraform.io/cloudflare/cloudflare tf_resource_type=cloudflare_zero_trust_gateway_policy @caller=github.com/hashicorp/terraform-plugin-framework@v1.15.0/internal/fwserver/server_planresourcechange.go:538 tf_req_id=ID tf_rpc=PlanResourceChange timestamp="...
```

**Comment by Kiblyn11** [comment]
Well it seems like it need to be all the fields set to default value [here](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5394#issuecomment-2905137052) 
I wanted to fix one by one and it doesn't work, `biso_admin_controls` will always request to change if you don't set the other values.

This is how I could fix this resource:

```
  rule_settings = {
    biso_admin_controls                = null
    block_page_enabled                 = false
    block_reason                       = ""
    insecure_disable_dnssec_validation = false
    ip_categories                      = false
    ip_indicator_feeds                 = false
    override_host                      = ""
}
```

**Comment by rexscaria** [comment]
Glad that it worked. This a small quick we faced with generating terraform definitions from API docs. Because of this, these are the minimum set of settings that need to be set in the TF definition.

Let us know if any other part of zerotrust policies are caught in plan apply cycles.

**Comment by Kiblyn11** [comment]
@rexscaria I spotted a remaining issue on this resource that always ask for change

```
resource "cloudflare_zero_trust_gateway_policy" "..." {
  account_id  = ...
  name        = "..."
  enabled     = true
  description = "..."
  precedence  = 12345
  action      = "resolve"
  filters     = ["dns_resolver"]
  traffic     = "..."
  rule_settings = {
    biso_admin_controls                = null
    block_page_enabled                 = false
    block_reason                       = ""
    insecure_disable_dnssec_validation = false
    ip_categories                      = false
    ip_indicator_feeds                 = false
    override_host                      = ""

    resolve_dns_through_cloudflare = false
    dns_resolvers = {
...
    }
  }
}
```

```
  # ... will be updated in-place
  ~ resource "cloudflare_zero_trust_gateway_policy" "..." {
      ~ created_at     = "..." -> (known after apply)
      + deleted_at     = (known after apply)
      + expiration     = (known after apply)
        id             = "..."
        name           = "..."
      ~ rule_settings  = {
          + biso_admin_controls                = (known after apply)
          + resolve_dns_through_cloudflare     = false
            # (7 unchanged attributes hidden)
        }
      ~ updated_at     = "..." -> (known after apply)
      ~ version        = 4 -> (known after apply)
      + warning_status = (known after apply)
        # (9 unchanged attributes hidden)
    }
```

**Comment by rexscaria** [comment]
Yeah the last one is a little strange. **resolve_dns_through_cloudflare** and **dns_resolvers** are mutually exclusive. So removing resolve_dns_through_cloudflare should fix that. We might have to fix these small errors by always returning all setting  always so that terraform can always assume it is present in the api. Now terraform gives different errors in different situations based on API response. Which is causing issues We will look into this improvement.

**Comment by KaydeeDee** [comment]
Hi there, reading through the comments I see the original issue has been resolved. Please let me know if you see it return.

**Comment by andrewmwhite** [comment]
I'm running into this issue as well, even when setting default values.

```
resource "cloudflare_zero_trust_gateway_policy" "example" {
  account_id  = local.personal_account_id
  name        = "office"
  description = "desc"
  precedence  = 1
  action      = "block"
  filters     = ["http"]
  traffic     = "http.request.uri == \"https://www.example.com/malicious\""
  rule_settings = {
    add_headers                        = {}
    block_page_enabled                 = false
    block_page_reason                  = "access not permitted"
    insecure_disable_dnssec_validation = false
    override_host                      = ""
    override_ips                       = []

    # Workaround for issue in the provider -- explicitly set default values.
    # https://github.com/cloudflare/terraform-provider-cloudflare/issues/5394#issuecomment-2905137052
    ip_categories       = false
    ip_indicator_feeds  = false
    check_session       = null
    l4override          = null
    biso_admin_controls = null
  }
  enabled  = true
  identity = "any(identity.saml_attributes[*] == \"groups=CFTAccessKubernetes\")"
}
```
```
Terraform will perform the following actions:

  # cloudflare_zero_trust_gateway_policy.example will be updated in-place
  ~ resource "cloudflare_zero_trust_gateway_policy" "example" {
      ~ created_at     = "2025-07-29T19:02:47Z" -> (known after apply)
      + deleted_at     = (known after apply)
      + expiration     = (known after apply)
        id             = "ca327b4f-53ef-4ef2-855c-bd63c2154d14"
        name           = "office"
      ~ rule_settings  = {
          + biso_admin_controls                = (known after apply)
          + block_page_enabled                 = false
          + insecure_disable_dnssec_validation = false
          + ip_categories                      = false
          + ip_indicator_feeds                 = false
          + override_host                      = ""
          + override_ips                       = []
            # (1 unchanged attribute hidden)
        }
      ~ updated_at     = "2025-07-29T19:02:47Z" -> (known after apply)
      ~ version        = 1 -> (known after apply)
      + warning_status = (known after apply)
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

[plan.redacted.log](https://github.com/user-attachments/files/21496494/plan.redacted.log)

**Comment by andrewmwhite** [comment]
Even setting `rule_settings` to exactly the suggested default values has the same issue:
```
resource "cloudflare_zero_trust_gateway_policy" "example" {
  account_id  = local.personal_account_id
  name        = "office"
  description = "desc"
  precedence  = 1
  action      = "block"
  filters     = ["http"]
  traffic     = "http.request.uri == \"https://www.example.com/malicious\""
  rule_settings = {
    # Workaround for issue in the provider -- explicitly set default values.
    # https://github.com/cloudflare/terraform-provider-cloudflare/issues/5394#issuecomment-2905137052
    block_page_enabled                 = false
    block_reason                       = ""
    insecure_disable_dnssec_validation = false
    ip_categories                      = false
    ip_indicator_feeds                 = false
    override_host                      = ""
    check_session                      = null
    add_headers                        = null
    l4override                         = null
    biso_admin_controls                = null
  }
  enabled  = true
  identity = "any(identity.saml_attributes[*] == \"groups=CFTAccessKubernetes\")"
}
```
```
Terraform will perform the following actions:
  # cloudflare_zero_trust_gateway_policy.example will be updated in-place
  ~ resource "cloudflare_zero_trust_gateway_policy" "example" {
      ~ created_at     = "2025-07-29T20:31:48Z" -> (known after apply)
      + deleted_at     = (known after apply)
      + expiration     = (known after apply)
        id             = "b28e9bec-e9f2-452c-a0dc-f54795254aa1"
        name           = "office"
      ~ rule_settings  = {
          + biso_admin_controls                = (known after apply)
          + block_page_enabled                 = false
          + block_reason                       = ""
          + insecure_disable_dnssec_validation = false
          + ip_categories                      = false
          + ip_indicator_feeds                 = false
          + override_host                      = ""
      ~ updated_at     = "2025-07-29T20:31:48Z" -> (known after apply)
      ~ version        = 1 -> (known after apply)
      + warning_status = (known after apply)
        # (8 unchanged attributes hidden)
Plan: 0 to add, 1 to change, 0 to destroy.
```

This is using terraform 1.7.3 with cloudflare/cloudflare 5.7.1 (latest).

[plan.redacted.log](https://github.com/user-attachments/files/21496901/plan.redacted.log)

**Comment by rexscaria** [comment]
Hello,

we have recently made changes to some gateway resources, and API payloads in order to fix these terraform issues. Which means waiting for the next version 5.8 will be the best option(scheduled to release by EOW).

But if this needs to be fixed sooner, you could try the following.
When i try the resource in the issue with the current provider, emptying rule_settings altogether works.


> resource "cloudflare_zero_trust_gateway_policy" "example" {
      account_id  = "<acc-id>"
      name        = "office"
      description = "desc"
      precedence  = 1
      action      = "block"
      filters     = ["http"]
      traffic     = "http.request.uri == \"https://www.example.com/malicious\""
      rule_settings = {}
      enabled  = true
      identity = "any(identity.saml_attributes[*] == \"groups=CFTAccessKubernetes\")"
}


this works for now, (and didn't work before because we had to tune the api payload to get this right).

From next terraform provider version, you can expect better support on all gateway resources at terraform.
