### ISSUE TITLE
cloudflare_zero_trust_tunnel_cloudflared_route detects changes on every plan and fails to apply

### ISSUE THREAD

**Issue by nr-nrobledo** [cloudflare/terraform-provider-cloudflare#5537]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.11.3
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v5.3.0
```

Every time I run a terraform plan changes are detected with the cloudflare_zero_trust_tunnel_cloudflared_route resource, but there shouldn't be any changes.  I've successfully applied at least once which created the initial config.  If I try to apply anyway I get an error for every instance of the resource.

### Affected resource(s)

cloudflare_zero_trust_tunnel_cloudflared_route

### Terraform configuration files

```hcl
resource "cloudflare_zero_trust_tunnel_cloudflared_route" "route_to_test" {
  account_id = var.cloudflare_account_id
  tunnel_id = "abbc2354-80f7-4324-af3d-omitted"
  network   = "192.168.250.0/24"
  comment   = "Test route"
}
```

### Link to debug output

https://gist.github.com/nr-nrobledo/ef76a2c2fa47d9062531cbc8d6082d3e

### Expected output

No changes and a successful apply

### Actual output

Plan:
```
  # cloudflare_zero_trust_tunnel_cloudflared_route.route_to_test will be updated in-place
  ~ resource "cloudflare_zero_trust_tunnel_cloudflared_route" "route_to_test" {
      ~ created_at         = "2025-04-29T18:42:46Z" -> (known after apply)
      + deleted_at         = (known after apply)
        id                 = "b2571e25-38e7-4816-8ed5-omitted"
      - virtual_network_id = "b667244b-1a5f-4545-omitted" -> null
        # (4 unchanged attributes hidden)
    }
```

Apply:
```
│ Error: failed to make http request
│
│   with cloudflare_zero_trust_tunnel_cloudflared_route.route_to_test,
│   on network_routes.tf line 30, in resource "cloudflare_zero_trust_tunnel_cloudflared_route" "route_to_test":
│   30: resource "cloudflare_zero_trust_tunnel_cloudflared_route" "route_to_test" {
│
│ PATCH "https://api.cloudflare.com/client/v4/accounts/omitted/teamnet/routes/b2571e25-38e7-4816-8ed5-omitted": 500 Internal Server Error {"success":false,"errors":[{"code":1000,"message":"Internal server
│ error"}],"messages":[],"result":null}
```

### Steps to reproduce

terraform plan
terraform apply

**Comment by gil-tohar-cyera** [comment]
I am seeing this issue as well. this resource cannot be reapplied, and so it's a broken resource type at the moment

**Comment by jhutchings1** [comment]
I have routed this to our internal tracking system for an engineer to have a look. Thank you!

**Comment by jemc** [comment]
Seeing the same with the latest provider version (`5.4.0`).

Does anyone know if there's an older version where this resource wasn't broken?

**Comment by jemc** [comment]
Answering my own question about older versions:

Here are all the versions I tested:
- `5.4.0` - has this bug
- `5.3.0` - has this bug
- `5.2.0` - has this bug
- `5.1.0` - this resource works properly
- `5.0.0` - this resource works properly

**Comment by peter-zsolt** [comment]
Until than we can use ignore changes.
```
  lifecycle {
    ignore_changes = [virtual_network_id]
  }
```

**Comment by musa-cf** [comment]
This should be fixed now in 5.5, but let us know if it's not!

**Comment by jemc** [comment]
Working for me in 5.5.0 👍

**Comment by nr-nrobledo** [comment]
Works now.  Thanks!

**Comment by F21** [comment]
This isn't working for me on 5.6.0 and 5.7.0 using OpenTofu 1.10.2.
Resources:
```terraform
resource "cloudflare_zero_trust_tunnel_cloudflared" "test" {
  account_id    = "REDACTED"
  name          = "testtest"
  config_src    = "cloudflare"
}

resource "cloudflare_zero_trust_tunnel_cloudflared_route" "test" {
  account_id = "REDACTED"
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.test.id
  network    = "10.0.0.1/32"
}
```

Output of `tofu apply`:
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu will perform the following actions:

  # cloudflare_zero_trust_tunnel_cloudflared_route.test will be updated in-place
  ~ resource "cloudflare_zero_trust_tunnel_cloudflared_route" "test" {
      ~ created_at         = "2025-07-15T04:38:40Z" -> (known after apply)
      + deleted_at         = (known after apply)
        id                 = "REDACTED"
      ~ virtual_network_id = "REDACTED" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_zero_trust_tunnel_cloudflared_route.test: Modifying... [id=REDACTED]
╷
│ Error: failed to make http request
│
│   with cloudflare_zero_trust_tunnel_cloudflared_route.test,
│   on main.tf line 60, in resource "cloudflare_zero_trust_tunnel_cloudflared_route" "test":
│   60: resource "cloudflare_zero_trust_tunnel_cloudflared_route" "test" {
│
│ PATCH "https://api.cloudflare.com/client/v4/accounts/REDACTED/teamnet/routes/REDACTED": 500 Internal Server Error
│ {"success":false,"errors":[{"code":1000,"message":"Internal server error"}],"messages":[],"result":null}
```
Running `apply` proposes changes `cloudflare_zero_trust_tunnel_cloudflared_route` every time and applying the plan will result in a 500 internal server error.

**Comment by hradaideh** [comment]
It still exists on 5.7
```
  # cloudflare_zero_trust_tunnel_cloudflared_route.x will be updated in-place
  ~ resource "cloudflare_zero_trust_tunnel_cloudflared_route" "x" {
      ~ created_at         = "2024-10-01T10:40:51Z" -> (known after apply)
      + deleted_at         = (known after apply)
        id                 = "x"
        # (5 unchanged attributes hidden)
    }
```

lifecycle ignore changes is not working as well

with 
```
│ Error: failed to make http request
│
│   with cloudflare_zero_trust_tunnel_cloudflared_route.x,
│   on routes.tf line 69, in resource "cloudflare_zero_trust_tunnel_cloudflared_route" "x":
│   69: resource "cloudflare_zero_trust_tunnel_cloudflared_route" "x" {
│
│ PATCH
│ "https://api.cloudflare.com/client/v4/accounts/x/teamnet/routes/x":
│ 500 Internal Server Error
│ {"success":false,"errors":[{"code":1000,"message":"Internal server
│ error"}],"messages":[],"result":null}
╵
ERRO[0137] Terraform invocation failed in x/Routes
```
