### ISSUE TITLE
5.4.0 broke cloudflare_workers_route (even more than it already was)

### ISSUE THREAD

**Issue by ceferrari** [cloudflare/terraform-provider-cloudflare#5553]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

After upgrading to version 5.4.0, which I was hoping would fix (https://github.com/cloudflare/terraform-provider-cloudflare/issues/5501#issuecomment-2850537278), I can no longer use this resource. The latest version not only didn't fix the issue, it broke it even more.

Before, I had to manually delete the route in my Cloudflare Dashboard before each Terraform run, which is a pain, but at least it worked. I set the route_id parameter and let it recreate the resource each time.

Now, my Terraform run will always fail because it no longer works with the route_id, nor without it!! (outputs below).

### Affected resource(s)

cloudflare_workers_route

### Terraform configuration files

```hcl
resource "cloudflare_workers_route" "this" {
  pattern  = "*.${var.zone_name}/*"
  route_id = cloudflare_workers_script.this.id
  script   = cloudflare_workers_script.this.id
  zone_id  = var.zone_id

  depends_on = [cloudflare_workers_script.this]
}
```

### Link to debug output

I am running it on Cloud Build

### Expected output

No errors.

### Actual output

With route_id:
```
│ Error: Unsupported argument
│
│   with module.worker.cloudflare_workers_route.this,
│   on ../../modules/worker/resource.tf line 31, in resource "cloudflare_workers_route" "this":
│   31:   route_id = cloudflare_workers_script.this.id
│
│ An argument named "route_id" is not expected here.
```

Without route_id:
```
│ Error: failed to make http request
│
│   with module.worker.cloudflare_workers_route.this,
│   on ../../modules/worker/resource.tf line 29, in resource "cloudflare_workers_route" "this":
│   29: resource "cloudflare_workers_route" "this" {
│
│ missing required route_id parameter
```

What the hell?

### Steps to reproduce

1. Use cloudflare_workers_route with route_id
2. Use cloudflare_workers_route without route_id

**Comment by jhutchings1** [comment]
Thanks for reporting, I've directed this to the team to take a look asap.

**Comment by musa-cf** [comment]
Hi @ceferrari! Can you provide TF debug logs? I'm not able to reproduce this behavior, and want to make sure I'm not missing something here.

I'm able to create, update, and delete a `workers_route` resource without setting a `route_id` at all.

**Comment by ceferrari** [comment]
> Hi [@ceferrari](https://github.com/ceferrari)! Can you provide TF debug logs? I'm not able to reproduce this behavior, and want to make sure I'm not missing something here.
> 
> I'm able to create, update, and delete a `workers_route` resource without setting a `route_id` at all.

Sure.

With `route_id`: https://gist.github.com/ceferrari/5648ec5997b83cc475bf8c7f1199cb1b
```
resource "cloudflare_workers_route" "this" {
  pattern  = "*.${var.zone_name}/*"
  route_id = cloudflare_workers_script.this.id
  script   = cloudflare_workers_script.this.id
  zone_id  = var.zone_id

  depends_on = [cloudflare_workers_script.this]
}
```

Without `route_id`: https://gist.github.com/ceferrari/5d5fa61d4cb54ecd5aff0ee3662ffa9a 
```
resource "cloudflare_workers_route" "this" {
  pattern  = "*.${var.zone_name}/*"
  script   = cloudflare_workers_script.this.id
  zone_id  = var.zone_id

  depends_on = [cloudflare_workers_script.this]
}
```

My: `cloudflare_workers_script`
```
resource "cloudflare_workers_script" "this" {
  account_id  = var.cloudflare.account_id
  script_name = "${var.env}-cloudflared-ping"

  main_module = "worker.js"
  observability = {
    enabled = true
  }

  content = <<-EOT
export default {
  async fetch(request) {
    try {
      for (let i = 1; i <= 100; i++) {
        const res = await fetch('https://${var.env}-cloudflared-${var.cloudflare.cloud_run_sufix}?t=' + Date.now(), { method: 'HEAD' });
        if (res.ok) break;
        else await new Promise((r) => setTimeout(r, 100));
      }
    } catch (err) {
      console.error('Tunnel failed to awake: ', err);
    }
    return fetch(request);
  },
};
  EOT
}
```

**Comment by maxwellpeterson** [comment]
Version 5.3.0 and lower incorrectly omitted the "id" attribute from state, please see this comment https://github.com/cloudflare/terraform-provider-cloudflare/issues/5501#issuecomment-2867496525

Once route state is correctly updated (e.g. by recreating the resource using version 5.4.0), the issue is resolved.

**Comment by cristim** [comment]
@maxwellpeterson  The problem is version 5.4.0 is still broken for basic things like creating an R2 bucket.

I have very simple code with just a handful of resources that creates a bucket with custom domain and a worker with a route. 

None of the 5.x versions I tried supports all these simple things together. Bucket creation is broken from 5.3 onwards, and routes seem to be working only in 5.4 if I read this correctly.

The quality of this provider seems very poor compared to any other providers I ever used so far. This would be acceptable from something at version 0.1 but not from 5.x.

Are there any integration tests that that run before releases are made to check if such basic resources keep working?

**Comment by jhutchings1** [comment]
@cristim let's keep this issue focused on the resource at hand. If your R2 issue isn't already reported, please open an additional issue so we can get it to the appropriate team. 

More generally: we've certainly found more issues than anticipated with the autogenerated v5 provider, but we're working across all the teams at the company to resolve the issues. We do have automated tests for Terraform, but the tests weren't sufficient to discover the issues users are reporting. I know that the current state is not satisfying and appreciate everyone's patience as we play catch up on v5.

**Comment by ceferrari** [comment]
> Once route state is correctly updated (e.g. by recreating the resource using version 5.4.0), the issue is resolved.

That is it. However, it would be nice if it were possible to automate this "state update", so people would avoid going through what I went through (and rollback to previous version).

**Comment by jhutchings1** [comment]
> > Once route state is correctly updated (e.g. by recreating the resource using version 5.4.0), the issue is resolved.
> 
> That is it. However, it would be nice if it were possible to automate this "state update", so people would avoid going through what I went through (and rollback to previous version).

@jacobbednarz Are we able to add this to the grit scripts?

**Comment by cristim** [comment]
thanks @jhutchings1, I understand this is a complex project and things are in flux but maybe you can mark it as alpha quality until all the basics are covered so people don't run into such issues.

Creating a bucket and a worker with a route should be among the integration tests. 

Feel free to take my code for this from https://github.com/LeanerCloud/cloud-instances.info/tree/9756e9b360a198a79b033ff1e36af20b273ff6ec/infra/terraform/cloudflare_ephemeral_infra

**Comment by jacobbednarz** [comment]
given we don't have a definitive way to determine who applied this work around and how it is being referenced, i wouldn't add it to the global ones to avoid breaking anyone who is relying on this in older versions.

instead, you can manually run the following on your state file to correct this (replacing `path/to/file.tfstate` accordingly).

```
grit apply --language json '`{ $..., "mode": "managed", "type": "$resource_type", $..., "instances":[$instances] }` where {
    $resource_type <: contains `cloudflare_workers_route`,
    $instances <: any {
        contains `"route_id": $_` => .
    }
}' path/to/file.tfstate
```

**Comment by ceferrari** [comment]
> And if you store your tfstate file in something like a GCS bucket, you would need to:
> 
> 1. Download the state file.
> 2. Use grit locally to manipulate the state file.
> 3. Upload the state file back to your GCS bucket as a new object version.
> 
> Something like that?

You could change your backend config to local, run `terraform init -migrate-state`, apply the changes to the state locally and then do the inverse to migrate the state back to GCS (change backend to gcs and run the command again). 

It's a bit painful this way, I know. That is why I suggested an automated way on my last comment.

**Comment by mspoonauer** [comment]
When I run the grit script, this is what happens:

```
    -            "route_id": null,
    +            ,
```

Do we want the comma?

**Comment by mspoonauer** [comment]
And if we're actually supposed to delete the line:

```
python3 -c '  
import json
import sys

with open("default.tfstate", "r") as f:
    state = json.load(f)
    # Check if original file had trailing newline
    f.seek(0, 0)
    original_content = f.read()
    had_trailing_newline = original_content.endswith("\n")

# Navigate through resources
for resource in state["resources"]:
    if "cloudflare_workers_route" in resource["type"]:
        for instance in resource["instances"]:
            if "attributes" in instance and "route_id" in instance["attributes"]:
                del instance["attributes"]["route_id"]

with open("new.tfstate", "w") as f:
    json.dump(state, f, indent=2)             
    # Add trailing newline if original had one
    if had_trailing_newline:
        f.write("\n")
'

diff default.tfstate.orig new.tfstate | more
98d97
<             "route_id": null,
```

**Comment by rupalims** [comment]
@markjmiller could you please take a peek at latesst feedback?

**Comment by jhutchings1** [comment]
Chatted with @1000hz on this one, and we think this one is addressed minus the migration issues. We're dealing with migration issues separately, so I'm closing this one out.
