### ISSUE TITLE
Terraform v5 Issues

### ISSUE THREAD

**Issue by jhutchings1** [cloudflare/terraform-provider-cloudflare#5573]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

5.4.0

### Affected resource(s)

Multiple

### Terraform configuration files

```hcl
N/A
```

### Link to debug output

N/A

### Expected output

 N/A

### Actual output

N/A

### Steps to reproduce

N/A

**Comment by bhartm3** [comment]
Hello, thanks for the statement this really helps us for planning and assess the v5 migration. We are also using modules heavily and some nuanced features in a large enterprise setting. We are using tf for nearly all configurations. We have the v5 migration project in the backlog and will keep watching over the coming months, and encourage you for further messages like this :+1:

**Comment by maxabaumgarten** [comment]
Thanks for this update. Can we get some sort of tracker that shows what still remains to migrated?

**Comment by stankolubomir** [comment]
Just wanted to chime in with some feedback on the recent releases. Nothing’s broken for us yet because we are not able to upgrade — we’ve had to hold off on updating our Cloudflare infrastructure because each new version seems to introduce some broken resources for us. It’s getting harder to believe that an upgrade won’t cause any more troubles.

What’s especially confusing is that the provider is now autogenerated, but there don’t seem to be tests catching these issues before release. Isn’t that kind of the whole point of automation — to make things safer and more consistent?

We really appreciate the effort that goes into maintaining this provider — we know it’s a lot. Just hoping you will be able to stabilize the v5 provider soon.

**Comment by jmreicha** [comment]
One thing that trips me up is that when a new version is released the diff in changes is so large that I can't parse through them and read through all the changes in the release notes. It would be great to get some indication of what is actually being addressed in those release notes, or break apart releases into smaller ones so we can track the things that getting fixed easier.

**Comment by burner1024** [comment]
Terraform LSP doesn't appear to be able to [pick up](https://github.com/hashicorp/terraform-ls/issues/1664#issuecomment-2799894337) 5.x, so upgrade isn't in the cards anyway.

**Comment by aurimasniekis** [comment]
Hi Team,

I'm not trying to be overly negative, but my experience with the Cloudflare v5 provider since early this year has been extremely frustrating. Out of all the providers I've used so far, this has been the roughest, including community managed ones. Honestly, it feels like it would be faster and better to just rewrite everything from scratch than try to work with that code generator you're currently using.

Some of the main issues I've encountered:
* The documentation often doesn't match the actual code or behavior.
* Things frequently break or stop working as expected, and fixes seem to take months.
* There's always something not aligning with each release or plan, even when nothing has changed on my end.
* Sub-resources are missing imports even when the main resource imports exist, making importing main resources pointless.

For example, after upgrading from `5.1` to `5.5` in an attempt to resolve issues with `cloudflare_r2_custom_domain`, I'm now facing over 400 `cloudflare_dns_record` resources that don't match. Even re-importing doesn't resolve these mismatches. On top of that, the sheer number of basic code issues introduced in the last release makes it feel like no real testing was done before shipping `5.5`, there are problems at the code level, not just with the API.

It's honestly surprising to see a provider in this state coming from a major company, right now it feels less reliable than several unofficial community providers I've used.

What would really help:
* Up-to-date documentation that actually matches the code and real world behavior.
* Faster fixes for blocking bugs and broken core features.
* More transparent, regular communication about what's being fixed and what's still not working.
* A compatibility tracker so users can quickly see what's safe to use and what's still broken.

I genuinely want to see this provider become stable and reliable, but right now it's just not usable for our needs. Please prioritize stability and accurate documentation above everything else. It's incredibly frustrating, and honestly embarrassing to have to explain to our clients, who are paying thousands for **Cloudflare Enterprise**, that these issues are out of our control and stem directly from Cloudflare...

Thanks,
Aurimas

**Comment by ikemo3** [comment]
Even the most basic `cloudflare_zone` data source with `filter` block doesn't work (see #5347), despite being documented in the official docs.

The migration guide provides no concrete solution for this fundamental zone filtering functionality. The first priority should be a comprehensive review of all issues closed as "Not Planned" - stop putting the burden on users to deal with broken basic features.

**Comment by elasticdotventures** [comment]
Please fix this soon.   I use `roo` code, it has aigentic editors that integrates with the LSP and attempts to fix syntax errors automatically, very annoying.

Terraform LSP cloudflare issues discussed here:
https://github.com/hashicorp/terraform-ls/issues/1664

**Comment by jhutchings1** [comment]
Hey everyone, just wanted to pop in and post a quick response on behalf of the team. We hear you on the pain, and I know the slow progress has been frustrating. The change to autogenerate the SDK for Terraform has had many more issues than we anticipated upon launch, and it's been a very different journey than any of the other autogenerated SDKs we've published which all went off without much difficulty.

We're working hard to fix all the issues across the resources, but unfortunately, the issues span many teams internally so we're negotiating with those teams on priority and timelines. If you're an enterprise customer and you're blocked on using Terraform right now, please reach out to your account team and let them know about the specific issues that you are blocked on. They can help add additional pressure to prioritize specific issues. 

We're continuing to run the community triage sessions weekly, and you're all welcome if you want to discuss a specific issue and get more insight into where it is. The link is in the readme.

**Comment by jhutchings1** [comment]
Addressing the comments from @aurimasniekis around the documentation, and changelogs: Our change to automatic SDK generation and documentation was intended to reduce drift between the docs and the SDKs, but for the moment it's worse for the SDKs. The API schemas and documentation publish continuously, but the SDKs do not. As a result, we're seeing drift between the SDK part of the docs and the API part. The docs for the Terraform provider that are published on [the registry](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs) should be more accurate right now because they are versioned. We have work identified in our plans for next quarter to improve those.

**Comment by aurimasniekis** [comment]
Just wanted to provide an update after upgrading to `5.6.0`... Unfortunately, I'm still seeing the same issues, none of the previous problems have been fixed, and now a few more things are actually broken. After upgrading and running `terraform plan`, I'm getting a whole new batch of mismatches, and applying the changes doesn't resolve them.

It's really disappointing that after a full month and another release, things are still getting worse instead of better. At this point, it feels like every upgrade introduces new issues rather than fixing the existing ones. Is there actually a plan in place to stabilize this provider, or should we just give up on using v5 for anything critical?

Would really appreciate some honest communication and a concrete roadmap for getting things back on track...

**Comment by Tirzono** [comment]
I recently started using the cloudflare provider and I immediately bumped into problems with the provider. This also led me to this issue and I'm wondering: what would you advice new users of the provider to use? Going for safe and using v4 or trying to embrace v5 and trying to work around all the issues? I understand that you want as much as possible people on v5 so that problems can be reported, but it might also scare a lot of (new) people away.

**Comment by jhutchings1** [comment]
@aurimasniekis I hear you on the pain. [The changelog](https://developers.cloudflare.com/changelog/2025-06-17-terraform-v560-provider/) has full details for the changes that went into 5.6.0 including the specific bugs that it resolved. We're still sitting at about 15% of resources with known issues despite the fixes. 
* [#5098: 500 Server Error on updating 'zero_trust_tunnel_cloudflared_virtual_network' Terraform resource ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5098)
* [#5148: cloudflare_user_agent_blocking_rule doesn’t actually support user agents ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5148)
* [#5472: cloudflare_zone showing changes in plan after following upgrade steps ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5472)
* [#5508: cloudflare_zero_trust_tunnel_cloudflared_config failed to serialize http request ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5508)
* [#5509: cloudflare_zone: Problematic Terraform behaviour with paused zones ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5509)
* [#5520: Resource 'cloudflare_magic_wan_static_route' is not working ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5520)
* [#5524: Optional fields cause crash in cloudflare_zero_trust_tunnel_cloudflared(s) when left null ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5524)
* [#5526: Provider v5 migration issue: no import method for cloudflare_zero_trust_device_default_profile_local_domain_fallback ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5526)
* [#5532: cloudflare_zero_trust_access_identity_provider detects changes on every plan ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5532)
* [#5561: cloudflare_zero_trust_tunnel_cloudflared: cannot rotate tunnel secret ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5561)
* [#5569: cloudflare_zero_trust_device_custom_profile_local_domain_fallback not allowing multiple DNS Server entries ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5569)
* [#5577: Panic modifying page_rule resource ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5577)
* [#5653: cloudflare_zone_setting resource schema confusion in 5.5.0: value vs enabled ↗](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5653)

If you are seeing new issues, please open issues for them. We are triaging the issues as they come in and working to get this stabilized as fast as possible across dozens of teams internally. I don't have a date for when things will be completed yet, but know that it's a major focus for the team. 

@Tirzono We encourage folks to check the list of resources with known issues and adopt v5 if they do not depend on any of those. Right now, we are tracking known issues on: 

| Resource name | 
| ----- | 
cloudflare_account
cloudflare_account_api_token_permission_groups_list
cloudflare_account_member
cloudflare_account_token
cloudflare_api_token
cloudflare_api_token_permission_groups_list
cloudflare_argo_smart_routing
cloudflare_authenticated_origin_pulls
cloudflare_authenticated_origin_pulls_certificate
cloudflare_certificate_pack
cloudflare_custom_ssl
cloudflare_dns_record
cloudflare_image_variant
cloudflare_list_item
cloudflare_logpull_retention
cloudflare_logpush_job
cloudflare_notification_policy_webhooks
cloudflare_pages_project
cloudflare_queue_consumer
cloudflare_r2_custom_domain
cloudflare_ruleset
cloudflare_workers_for_platforms_dispatch_namespace
cloudflare_workers_kv
cloudflare_workers_route
cloudflare_workers_script
cloudflare_zero_trust_access_application
cloudflare_zero_trust_access_applications
cloudflare_zero_trust_access_identity_provider
cloudflare_zero_trust_access_mtls_certificate
cloudflare_zero_trust_access_policy
cloudflare_zero_trust_device_custom_profile
cloudflare_zero_trust_device_custom_profile_local_domain_fallback
cloudflare_zero_trust_device_default_profile
cloudflare_zero_trust_dlp_custom_profile
cloudflare_zero_trust_dlp_entry
cloudflare_zero_trust_gateway_certificate
cloudflare_zero_trust_gateway_policy
cloudflare_zero_trust_gateway_settings
cloudflare_zero_trust_tunnel_cloudflared
cloudflare_zone_setting
cloudflare_zone_subscription

**Comment by ghost** [comment]
Some more feedback, @jhutchings1:

The API spec and provider still feel very unstable.

For example, this commit changes `run_worker_first` in `cloudflare_workers_script` from a boolean to a list of strings and removes `serve_directly`:
https://github.com/cloudflare/terraform-provider-cloudflare/commit/df6b8bfe1635c5b1809564a15c6ed0c1a39375f2
Sure enough, the same changes were made to the API docs (though the actual API still seems to accept a boolean):
https://developers.cloudflare.com/api/resources/workers/subresources/scripts/methods/update/
The provider doc still has `run_worker_first` as a boolean and includes `serve_directly`.

Filing bug reports for each bit of brokenness doesn't feel very practical when the issue template takes time to fill out, and each release has new regressions.  I'd usually go ahead and send a PR to fix little issues like this, but this repo only has the auto-generated output from systems that aren't open.

There's OpenAPI tooling for automatically detecting these kinds of breaking changes, so maybe there's room for QA tooling/processes to make a big difference.

**Comment by aurimasniekis** [comment]
Yep....

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/workers_script#run_worker_first-1

**Comment by aurimasniekis** [comment]
A week later, and the docs are still incorrect 🤷‍♂️

**Comment by jhutchings1** [comment]
> For example, this commit changes `run_worker_first` in `cloudflare_workers_script` from a boolean to a list of strings and removes `serve_directly`:

I looped back with the team that made those changes. WE do have automation, but it didn't catch this breaking change for whatever reason. Thanks for flagging!

**Comment by ghost** [comment]
Thanks, @jhutchings1!

This repo doesn't have issues enabled: https://github.com/cloudflare/api-schemas  Would it make sense to have a place to report stuff like this?  If I use the issue template here, I have to fill out irrelevant stuff like TF debug logs, and the fix would be upstream, anyway.

**Comment by gyoza** [comment]
> Even the most basic `cloudflare_zone` data source with `filter` block doesn't work (see [#5347](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5347)), despite being documented in the official docs.
> 
> The migration guide provides no concrete solution for this fundamental zone filtering functionality. The first priority should be a comprehensive review of all issues closed as "Not Planned" - stop putting the burden on users to deal with broken basic features.

This issue is concerning to me. The suggestion by contributors fail and do not work. Then the issue is closed as 'Not Planned', what is one supposed to do?

**Comment by jhutchings1** [comment]
> > Even the most basic `cloudflare_zone` data source with `filter` block doesn't work (see [#5347](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5347)), despite being documented in the official docs.
> > The migration guide provides no concrete solution for this fundamental zone filtering functionality. The first priority should be a comprehensive review of all issues closed as "Not Planned" - stop putting the burden on users to deal with broken basic features.
> 
> This issue is concerning to me. The suggestion by contributors fail and do not work. Then the issue is closed as 'Not Planned', what is one supposed to do?

@gyoza please feel free to open an issue if you're blocked. We're also running live triage sessions every Monday afternoon (PST) (link is in the README) where we are happy to chat through things if you're not happy with a resolution or need more help. Thanks!

**Comment by elasticdotventures** [comment]
> > > Even the most basic `cloudflare_zone` data source with `filter` block doesn't work (see [#5347](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5347)), despite being documented in the official docs.
> > > The migration guide provides no concrete solution for this fundamental zone filtering functionality. The first priority should be a comprehensive review of all issues closed as "Not Planned" - stop putting the burden on users to deal with broken basic features.
> > 
> > 
> > This issue is concerning to me. The suggestion by contributors fail and do not work. Then the issue is closed as 'Not Planned', what is one supposed to do?
> 
> [@gyoza](https://github.com/gyoza) please feel free to open an issue if you're blocked. We're also running live triage sessions every Monday afternoon (PST) (link is in the README) where we are happy to chat through things if you're not happy with a resolution or need more help. Thanks!

Hi @gyoza, any update here? This has been open nearly two months. I reached out June 3rd, @jhutchings1 on May 13th.

I’ve since worked around the issue by moving our deployment to another cloud. But frankly, stability in a Terraform provider should be table stakes — regardless of company size. Leaving this unresolved reflects poorly on the project and the org.

Thanks.

**Comment by jhutchings1** [comment]
@elasticdotventures I'm very sorry for your experience here, as I've mentioned a number of times in this thread and elsewhere, this project is taking longer to stabilize than we anticipated and we're working on it. We're making progress and have buy-in from leadership on the priority. It's still a very big project, so it will take time to get all the known issues addressed. My goal has been to ensure we are being as transparent as possible throughout this process. My GitHub profile has my contact information in it (DMs open on LinkedIn and X), you're welcome to reach out directly to me as well if you've got additional feedback. Thanks!

**Comment by jhutchings1** [comment]
Hey all, I know there's been a lot of anticipation for the 5.7.0 release which has a lot of fixes in it. The team has been working through that release process this week, and has been working to clear some regressions identified by the test suite. We've made the decision to delay the release to next week and are now aiming for Monday. 

Going forward, we're looking to shorten our release cadence to be closer to every 2 weeks. @KaydeeDee will be following up in the near future with an estimated release calendar. Thank you for your patience on this one! https://github.com/cloudflare/terraform-provider-cloudflare/pull/5669

**Comment by brennoo** [comment]
I know the team is busy with V5 but can we also cut a release for V4 while V5 is not stable? 
we have for example https://github.com/cloudflare/terraform-provider-cloudflare/pull/5708 that we wanted in V4 in the meantime 🙏

**Comment by aurimasniekis** [comment]
I'm genuinely curious... Do you guys test fixes before releasing them? In this case, it seems like the issue was marked as fixed, but after "fixing" the issue, your code generation process reverted the changes:
[Compare commit diff](https://github.com/cloudflare/terraform-provider-cloudflare/compare/de3965a07b17feda13b99b91e2330e22803288d7...c449dedccade8be6fb9c8b1ac02e293bb9cae709).

You then released version `5.7.0` and closed the issue ([#5733](https://github.com/cloudflare/terraform-provider-cloudflare/issues/5733)) as "FIXED", but the issue was never fixed...

**Comment by F21** [comment]
I previously tried to upgrade to v5.1 in a workspace that manages our Zero Trust apps and config, but there were too many issues and since I hadn't touched my state, I just kept the changes stored in another branch.

I just spent the last few days moving smaller parts of my infra over to v5.6/5.7 in the hopes that things have stabilised. I also moved my state over the v5, but it ended up breaking my infra and I had to manually log into machines to fix things. But I am currently in a place where my state has been updated (I do have a back up of the state before moving to v5) and the bits I need are 70% to 80% there.
The issues I am experiencing are mainly centered around:
- Resources being changed on every apply, when no changes are made. Example: `cloudflare_zero_trust_tunnel_cloudflared_route` had this issue and was fixed, but I am still experiencing it on 5.6 and 5.7: #5537 
- The API rejecting valid requests or crashing to 500: #5754 and #5537 

So I am currently in a place where I don't really want to restore state and revert my changes, but I am unable to move forward as those bugs are blocking and I don't really want to `apply` again and mangle my infra and then manually intervene.

**Comment by andrewmwhite** [comment]
We are basically blocked on migrating to v5. Setting aside any problems in v5 itself, the migration path is untenable. 

1. The guide suggests doing state surgery with `grit`, but the `grit` patterns provided don't cover all the changes. They also don't support modules.
2. We have hundreds of HCP Terraform workspaces that depend on this provider. We can't realistically do manual state surgery on each one. 
3. All the old schemas have been deleted, so we can't use `removed` blocks paired with `import` blocks, which is the only way to do a migration in configuration when you change a resource type name.
4. For `cloudflare_tunnel_route` -> `cloudflare_zero_trust_tunnel_cloudflared_route`: The new resource is identified by a UUID that _doesn't exist_ in previous versions of the state. I have to look up the ID from the API in order to migrate from v3/v4 to v5.

**Comment by jhutchings1** [comment]
@andrewmwhite do you mind opening an issue on your migration challenges? Want to keep this issue focused on the overall status of the project. The team has been recently strengthening the acceptance tests and reviewing all the migration scripts to reduce some of the edge cases, but we're still working through a lot of challenges so stabilization is slower than we want it to be.

**Comment by AleksandrKls** [comment]
@jhutchings1 Do you have some ETA when all list of broken resources must be fixed? 

I see in issues that version 5.11 still not stable :(

**Comment by jhutchings1** [comment]
@AleksandrKls It's been an ongoing project across the company and we're expecting it'll be in good shape by Q1. Please see @KaydeeDee 's issue here for the latest: https://github.com/cloudflare/terraform-provider-cloudflare/issues/6237

**Comment by c-ameron** [comment]
Hi @jhutchings1 
Will there be any further review of the `cloudflare_ruleset` resource not allowing to have individual rules? It's impossible to modularise the rules, and it makes very difficult to use when having a zone with lots of rules. From my understanding this is due to the backend API implementation.

This has been a significant source of frustration for me as an Enterprise Customer (something I've raised internally to Cloudflare in my feedback sessions with your engineers and our TAM), and having spoken to other Enterprise users I know they share the same frustration.

I see you commented on it before - is there any news on this?
https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210#issuecomment-2852527552

Related issues:
https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2907, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2423, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2688, #3207

Happy to link privately and discuss this further.

Thanks

**Comment by jhutchings1** [comment]
> Hi @jhutchings1 
> Will there be any further review of the `cloudflare_ruleset` resource not allowing to have individual rules? It's impossible to modularise the rules, and it makes very difficult to use when having a zone with lots of rules. From my understanding this is due to the backend API implementation.
> 
> This has been a significant source of frustration for me as an Enterprise Customer (something I've raised internally to Cloudflare in my feedback sessions with your engineers and our TAM), and having spoken to other Enterprise users I know they share the same frustration.
> 
> I see you commented on it before - is there any news on this?
> https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210#issuecomment-2852527552
> 
> Related issues:
> https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2907, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2423, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2688, #3207
> 
> Happy to link privately and discuss this further.
> 
> Thanks
> 

@c-ameron  Thanks for your question. The Terraform provider is a thin wrapper over the API, so big changes will depend on shifts in the upstream API. I'll ping this thread to the rulesets team and let them weigh in here

**Comment by smarsh-cf** [comment]
> Hi [@jhutchings1](https://github.com/jhutchings1) Will there be any further review of the `cloudflare_ruleset` resource not allowing to have individual rules? It's impossible to modularise the rules, and it makes very difficult to use when having a zone with lots of rules. From my understanding this is due to the backend API implementation.
> 
> This has been a significant source of frustration for me as an Enterprise Customer (something I've raised internally to Cloudflare in my feedback sessions with your engineers and our TAM), and having spoken to other Enterprise users I know they share the same frustration.
> 
> I see you commented on it before - is there any news on this? [#3210 (comment)](https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210#issuecomment-2852527552)
> 
> Related issues: [#3210](https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210), [#2907](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2907), [#2423](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2423), [#2688](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2688), [#3207](https://github.com/cloudflare/terraform-provider-cloudflare/pull/3207)
> 
> Happy to link privately and discuss this further.
> 
> Thanks

Moving away from managing as 'rulesets' vs managing as individual rules is a very big lift given how this system is architected. The non-dashboard UX for Rules management is a topic we want to improve for sure, but there are no immediate plans on the horizon. We expect to revisit this topic in earnest in 2026.

**Comment by james-callahan** [comment]
> If you are seeing new issues, please open issues for them. We are triaging the issues as they come in and working to get this stabilized as fast as possible across dozens of teams internally. I don't have a date for when things will be completed yet, but know that it's a major focus for the team.

Attempting to migrate to v5 I hit an apparent block with custom log fields (which is also via `cloudflare_ruleset`): https://github.com/cloudflare/terraform-provider-cloudflare/issues/6439

**Comment by c-ameron** [comment]
> > Hi [@jhutchings1](https://github.com/jhutchings1) Will there be any further review of the `cloudflare_ruleset` resource not allowing to have individual rules? It's impossible to modularise the rules, and it makes very difficult to use when having a zone with lots of rules. From my understanding this is due to the backend API implementation.
> > 
> > This has been a significant source of frustration for me as an Enterprise Customer (something I've raised internally to Cloudflare in my feedback sessions with your engineers and our TAM), and having spoken to other Enterprise users I know they share the same frustration.
> > 
> > I see you commented on it before - is there any news on this? [#3210 (comment)](https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210#issuecomment-2852527552)
> > 
> > Related issues: [#3210](https://github.com/cloudflare/terraform-provider-cloudflare/issues/3210), [#2907](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2907), [#2423](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2423), [#2688](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2688), [#3207](https://github.com/cloudflare/terraform-provider-cloudflare/pull/3207)
> > 
> > Happy to link privately and discuss this further.
> > 
> > Thanks
> 
> Moving away from managing as 'rulesets' vs managing as individual rules is a very big lift given how this system is architected. The non-dashboard UX for Rules management is a topic we want to improve for sure, but there are no immediate plans on the horizon. We expect to revisit this topic in earnest in 2026.

Hi @smarsh-cf , has there been any discussion or prioritisation on the rules management so far? We're still constantly getting affected by this issue.

Thanks

**Comment by KaydeeDee** [comment]
Closing this thread as there are two new pinned issues that are more up to date: the new migration tool (https://github.com/cloudflare/terraform-provider-cloudflare/issues/7022) and the list of stable resources: https://github.com/cloudflare/terraform-provider-cloudflare/issues/6237 

Please create a new issue is something comes up!
