### ISSUE TITLE
cloudflare_load_balancer_monitor consecutive_down/consecutive_up

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [cloudflare/terraform-provider-cloudflare#5676]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

```
      + consecutive_down = 0
      + consecutive_up   = 0
```
It shows up on the plan no matter how many times I apply it successfully. No matter if specified on the code explicitly - `consecutive_down = 0` or when not set and using the default `0` value:

```

  # cloudflare_load_balancer_monitor.monitor0["abc"] will be updated in-place
  ~ resource "cloudflare_load_balancer_monitor" "monitor0" {
      + consecutive_down = 0
      + consecutive_up   = 0
      ~ created_on       = "2025-06-19T10:49:06.755962Z" -> (known after apply)
        id               = "1f0776a2ff31e46c56216d96e85121d8"
      ~ modified_on      = "2025-06-19T10:56:13.390072Z" -> (known after apply)
        # (14 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

Using the most recent `5.6.0` provider:
```
terraform providers

Providers required by configuration:
.
└── provider[registry.terraform.io/cloudflare/cloudflare] ~> 5.6.0

Providers required by state:

    provider[registry.terraform.io/cloudflare/cloudflare]


```

### Affected resource(s)

cloudflare_load_balancer_monitor

**Comment by johnmarcou** [comment]
Same issue here. It looks like it has been introduced into `5.2.0`. Issue happens when `consecutive_down` and/or `consecutive_up` are non-provided, set to `null` or `0`. If `> 1`, then the issue disappears.

**Comment by brunohaid** [comment]
Same here, with both 5.6.0 and 5.5.0. Also tried ton of `ignore_changes` variations but unable suppress it showing up with every plan / apply.

**Comment by jhutchings1** [comment]
Thanks for letting us know, I've opened a new issue internally for the team to investigate.

**Comment by alicancakil** [comment]
issue exists in `5.7.1` as well.

**Comment by jhutchings1** [comment]
This one should be fixed in the next release (5.9).

**Comment by vedhavyas** [comment]
Not only the consecutive up or down but for path as well.

From the docs, if my type is tcp then path is not valid so i did not set one but when I plan again, I see this change

```
~ resource "cloudflare_load_balancer_monitor" "domain_rpc_health_check" {
      ~ created_on       = "2025-08-04T15:27:48.183693Z" -> (known after apply)
        id               = "<REDACTED>"
      ~ modified_on      = "2025-08-07T07:16:20.197185Z" -> (known after apply)
      + path             = "/"
        # (15 unchanged attributes hidden)
    }
```

So I went and set the path to "/" and still does not change and gives me the same output anyway

**Comment by jhutchings1** [comment]
> This one should be fixed in the next release (5.9).

Closing per this. Thanks!

**Comment by vedhavyas** [comment]
This is not solved with 5.10.1

I'm still seeing the updates in place for load_balancer_monitor

**Comment by brunohaid** [comment]
"Works on my machine", ie issue resolved with `5.10.1` on OpenTofu `1.10.6` / `darwin_arm64`.
