### ISSUE TITLE
`cloudflare_account_token` does not support nested resources in policies (API does, and import fails)

### ISSUE THREAD

**Issue by aurimasniekis** [cloudflare/terraform-provider-cloudflare#5733]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.11.4
+ provider registry.terraform.io/cloudflare/cloudflare v5.6.0

### Affected resource(s)

cloudflare_account_token
cloudflare_api_token (possibly too?)

### Terraform configuration files

```hcl
resource "cloudflare_account_token" "token" {
  account_id = var.account_id
  name       = "token"
  policies    = [
    {
      effect            = "allow"
      resources         = {
        "com.cloudflare.api.account.zone.*" = "*"
      }
      permission_groups = [
        // ...
      ]
    },
    {
      effect            = "allow"
      permission_groups = [
        // ...
      ]
      resources         = {
        "com.cloudflare.api.account.${var.account_id}" = "*"
      }
    },
  ]
}
```

### Link to debug output

Not needed

### Expected output

Terraform should either:

* allow nested `resources` (like `"com.cloudflare.api.account.zone.*"` as keys with sub-resources), consistent with Cloudflare’s API,
* or the schema should reject them clearly and import should reflect the limitations.

Also, `terraform import` should fully and correctly import the existing token's resources, including nested structure where applicable.

### Actual output

On apply with valid nested resources:
```
│ Error: failed to make http request
│ 
│   with cloudflare_account_token.this_token,
│   on tokens.tf line 39, in resource "cloudflare_account_token" "token":
│   39: resource "cloudflare_account_token" "token" {
│ 
│ PUT "https://api.cloudflare.com/client/v4/accounts/xxxxxxxx":
│ 400 Bad Request {"success":false,"errors":[{"code":1001,"message":"Must specify a zone for account owned tokens, or nest zone under specific account resource"}],"messages":[],"result":null}
```
On import of an existing token with nested resources:

```
│ Inappropriate value for attribute "policies": element 0: attribute "resources" is required.
```

### Steps to reproduce

1. Create a token via Cloudflare dashboard or API that includes nested resource scopes.
2. Run `terraform import cloudflare_account_token.token <account_id>/<token_id>`.
3. Observe missing nested `resources` in imported state and failure on next apply.
4. Try manually defining nested resources in HCL as per API behavior.
5. Observe 400 error from API during Terraform apply.

### Additional factoids

* The Cloudflare API clearly supports nested resource definitions under "resources" in token policies.
* The Terraform provider schema currently doesn’t align with this and breaks both creation and import.
* Codegen might be missing this nuance from the OpenAPI schema.

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/5233

**Comment by aurimasniekis** [comment]
Web UI interface creates tokens with nested resources without issue and it's not possible to recreate this or even import the token into terraform...

```json
{
  "name": "Read all resources",
  "condition": {},
  "policies": [
    {
      "effect": "allow",
      "resources": {
        "com.cloudflare.api.account.<account_id>": "*"
      },
      "permission_groups": []
    },
    {
      "effect": "allow",
      "resources": {
        "com.cloudflare.api.account.<account_id>": {
          "com.cloudflare.api.account.zone.*": "*"
        }
      },
      "permission_groups": []
    }
  ]
}
```

**Comment by KaydeeDee** [comment]
Hi there - this issue is fixed in our upcoming release of 5.7, which is going out today! Please let us know if you see this come up again after using 5.7.

**Comment by aurimasniekis** [comment]
@KaydeeDee It was not fixed... Same as it was in 5.6.0

**Comment by aurimasniekis** [comment]
Your code gen reverted the changes (which maybe would had fixed it...)

https://github.com/cloudflare/terraform-provider-cloudflare/commit/c449dedccade8be6fb9c8b1ac02e293bb9cae709

**Comment by nlsandler** [comment]
Hi @aurimasniekis - thanks for flagging that this hasn't been resolved, and sorry about that! This is running into a limitation of our codegen algorithm. I've created a ticket internally to address that so we can fix this issue for real in the next release.

**Comment by aurimasniekis** [comment]
Hi @nlsandler - `5.7.1` was released and it's still not fixed...

**Comment by nlsandler** [comment]
Sorry, my earlier comment was unclear! I meant the next release after 5.7.1 (since 5.7.1 went out the day I commented). It looks like the necessary fix here is to make the `policies` attribute dynamic so it can support both kinds of resources. Right now my expectation is that it won't be fixed in 5.8, unfortunately - we'll update this issue once this lands.

**Comment by aurimasniekis** [comment]
Hi @nlsandler, 5.8.2 was just released and unfortunately, the issue is still not fixed.

At this point, it's really difficult to explain to our clients, many of whom are Cloudflare Enterprise customers, why the most critical feature, account/user tokens, still isn't supported properly. This feature is essential for automating integrations, and without it, they are stuck manually managing thousands of tokens across environments, which is completely unsustainable.

Is there any clear timeline or commitment for when this will be properly addressed? The current situation is blocking key automation use cases for large customers...

**Comment by aurimasniekis** [comment]
@nlsandler Any chance this is getting fixed with the `5.9` release?

**Comment by nlsandler** [comment]
Hi @aurimasniekis, unfortunately I don't believe this will be fixed in the 5.9 release. I totally understand your frustration here - we recognize that this is a critical resource and this issue is causing pain for you and your customers. Unfortunately, the number of resources with outstanding issues is forcing us to make tough decisions about what to prioritize in each release.

**Comment by aurimasniekis** [comment]
You literally just need to apply the commit from the previous fix, why is this so hard? Do I need to fork the provider and maintain it separately just to get this resolved? It’s been over a month, and in the meantime what am I supposed to tell my customers, that they have to hand-craft thousands of tokens because we can’t get a simple patch merged?

Who should I tell my customers (Enterprise plan users) to contact in their support channel to put this on high priority?

https://github.com/cloudflare/terraform-provider-cloudflare/commit/c449dedccade8be6fb9c8b1ac02e293bb9cae709

**Comment by KaydeeDee** [comment]
@aurimasniekis - We understand you're frustrated but all comments and requests need to be kind and respectful. We will not be responding to comments that do not adhere to that. We have had to make a range of very difficult prioritization calls in order to stabilize v5 and we are releasing every 2 weeks to keep those improvements ongoing. 

With that said, any enterprise customers should reach out to their Cloudflare support folks (they will know who this is) and the will submit an internal ticket. Thank you.

**Comment by josefguenther** [comment]
I'm still getting this error on 5.9. Honestly since this bug was known for so long, acknowledged, and fixes were promised and attempted but it still hasn't been resolved and now you're saying you don't care much about it anymore, this gives me very very little confidence in cloudflare.

**Comment by josefguenther** [comment]
Still an issue on v5.11.0

**Comment by dsalaza4** [comment]
@KaydeeDee @nlsandler Please consider giving higher priority to issues related to `cloudflare_api_token` and `cloudflare_account_token` as these resources are pretty much the foundation of everything. If we can't properly manage tokens, then we can't do anything else. 

Another very impactful issue affecting tokens is https://github.com/cloudflare/terraform-provider-cloudflare/issues/5710, it basically breaks the ability to modify tokens via terraform

**Comment by KaydeeDee** [comment]
Hey @dsalaza4 - you have my full agreement that this is an important issue. I have reached out to the team that would be leading this fix to get an update. I completely empathize with your frustration - I'll follow up here as soon as I hear back.

**Comment by camaeel** [comment]
~~After upgrading to 5.13.0 my coded stopped working due to:~~
```
  │ 
  │ Inappropriate value for attribute "policies": element 0: attribute
  │ "resources": string required.
```

~~Same code works for me in 5.9.0 and 5.10.1.~~

~~My code:~~
```
resource "cloudflare_api_token" "dns_edit_all_account" {
  name = "${local.cluster_name}-cert-issuer"

  # include all zones from specific account
  policies = [
    {
      effect = "allow"
      permission_groups = [
        {
          id = local.permission_map["DNS Read"]
        },
        {
          id = local.permission_map["DNS Write"]
        },
      ]
      resources = {
        "com.cloudflare.api.account.zone.${data.cloudflare_zone.zone.zone_id}" = "*"
      }
    }
  ]
  status = "active"
}
```

I didn't expect breakign change in Minor release: https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v5.13.0. This should be a Major release if it includes breaking changes (https://semver.org/#summary)

**Comment by fholzer** [comment]
Until v5.13 you could only create tokens containing policies with account scope. With v5.13 account and zone scope are supported. This is fixed for me.

**Comment by KaydeeDee** [comment]
Hi everyone - you should see this fixed in our latest release. Please note, a breaking change was introduced in order to fix this issue - please read the changelog here: https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v5.13.0 

Let me know if you see anything come back up.
