### ISSUE TITLE
v5.6 not compatible with opentofu

### ISSUE THREAD

**Issue by pcanham** [cloudflare/terraform-provider-cloudflare#5748]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

OpenTofu v1.10.2
on darwin_amd64
+ provider registry.opentofu.org/cloudflare/cloudflare v5.6.0
+ provider registry.opentofu.org/hashicorp/http v3.5.0
+ provider registry.opentofu.org/hashicorp/local v2.5.3
+ provider registry.opentofu.org/hashicorp/null v3.2.4
+ provider registry.opentofu.org/hashicorp/tls v4.1.0

### Affected resource(s)

cloudflare_zero_trust_access_identity_provider

### Terraform configuration files

```hcl
resource "cloudflare_zero_trust_access_identity_provider" "azure_idp" {
  account_id = var.cloudflare_account_id
  name       = var.azuread_idp_name
  type       = "azureAD"
  config = {
    client_id      = var.azuread_idp_client_id
    client_secret  = var.azuread_idp_client_secret
    directory_id   = var.azuread_idp_directory_id
    support_groups = var.azuread_idp_support_groups
  }
  scim_config = {
    enabled                  = var.azuread_idp_scim_enabled
    group_member_deprovision = var.azuread_idp_scim_group_member_deprovision
    seat_deprovision         = var.azuread_idp_scim_seat_deprovision
    user_deprovision         = var.azuread_idp_scim_user_deprovision
  }
  lifecycle {
    ignore_changes = [
      config
    ]
  }
}
```

### Link to debug output

Due to the resource type no debug output shared to avoid leaking identity provider details

### Panic output

│ Error: WriteOnly Attribute Not Allowed
│ 
│   with cloudflare_zero_trust_access_identity_provider.azure_idp,
│   on access_identity_provider.tofu line 1, in resource "cloudflare_zero_trust_access_identity_provider" "azure_idp":
│    1: resource "cloudflare_zero_trust_access_identity_provider" "azure_idp" {
│ 
│ The resource contains a non-null value for WriteOnly attribute config.client_secret. Write-only attributes are only supported in Terraform
│ 1.11 and later.
╵

### Expected output

No Error

### Actual output

│ Error: WriteOnly Attribute Not Allowed
│ 
│   with cloudflare_zero_trust_access_identity_provider.azure_idp,
│   on access_identity_provider.tofu line 1, in resource "cloudflare_zero_trust_access_identity_provider" "azure_idp":
│    1: resource "cloudflare_zero_trust_access_identity_provider" "azure_idp" {
│ 
│ The resource contains a non-null value for WriteOnly attribute config.client_secret. Write-only attributes are only supported in Terraform
│ 1.11 and later.
╵

### Steps to reproduce

1. attempt to create a idp with opentofu

**Comment by yruss972** [comment]
Might be wrong but seems this is more an issue of the entire provider no longer being compatible with Terraform < 1.11

**Comment by KaydeeDee** [comment]
Hi there - This is fixed in v5.7, which is coming out today! Please let us know if you come across it again.

**Comment by ruzickap** [comment]
FYI:

I have the same issue when using the `cloudflare_zero_trust_access_identity_provider` with `v5.7` CloudFlare provider:

```hcl
terraform {
  required_version = "~> 1.9"
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "5.7.0"
    }
  }
}

provider "cloudflare" {}
...
...
...
resource "cloudflare_zero_trust_access_identity_provider" "google_oauth" {
  name       = "Google IDP"
  type       = "google"
  account_id = var.cloudflare_account_id
  config = {
    client_id     = var.cloudflare_zero_trust_access_identity_provider_google_oauth_client_id
    client_secret = var.cloudflare_zero_trust_access_identity_provider_google_oauth_client_secret
  }
}
```

Tofu apply:

```
❯ tofu apply
╷
│ Error: WriteOnly Attribute Not Allowed
│
│   with cloudflare_zero_trust_access_identity_provider.google_oauth,
│   on zerotrust.tf line 130, in resource "cloudflare_zero_trust_access_identity_provider" "google_oauth":
│  130: resource "cloudflare_zero_trust_access_identity_provider" "google_oauth" {
│
│ The resource contains a non-null value for WriteOnly attribute config.client_secret. Write-only attributes are only supported in Terraform 1.11 and later.
```

**Comment by pcanham** [comment]
Issue still not resolved

```
OpenTofu v1.9.1
on darwin_arm64
+ provider registry.opentofu.org/cloudflare/cloudflare v5.7.1
+ provider registry.opentofu.org/hashicorp/http v3.5.0
+ provider registry.opentofu.org/hashicorp/local v2.5.3
+ provider registry.opentofu.org/hashicorp/null v3.2.4
+ provider registry.opentofu.org/hashicorp/tls v4.1.0
```

```
│ Error: WriteOnly Attribute Not Allowed
│
│   with cloudflare_zero_trust_access_identity_provider.azure_idp,
│   on access_identity_provider.tofu line 1, in resource "cloudflare_zero_trust_access_identity_provider" "azure_idp":
│    1: resource "cloudflare_zero_trust_access_identity_provider" "azure_idp" {
│
│ The resource contains a non-null value for WriteOnly attribute config.client_secret. Write-only attributes are only supported in Terraform 1.11
│ and later.
╵
```

```
resource "cloudflare_zero_trust_access_identity_provider" "azure_idp" {
  account_id = var.cloudflare_account_id
  name       = var.azuread_idp_name
  type       = "azureAD"
  config = {
    client_id      = var.azuread_idp_client_id
    client_secret  = var.azuread_idp_client_secret
    directory_id   = var.azuread_idp_directory_id
    support_groups = var.azuread_idp_support_groups
  }
  scim_config = {
    enabled                  = var.azuread_idp_scim_enabled
    group_member_deprovision = var.azuread_idp_scim_group_member_deprovision
    seat_deprovision         = var.azuread_idp_scim_seat_deprovision
    user_deprovision         = var.azuread_idp_scim_user_deprovision
  }
  lifecycle {
    ignore_changes = [
      config
    ]
  }
}
```

**Comment by jimmyjones2** [comment]
@KaydeeDee Can this issue be reopened please as it's not resolved

**Comment by pcanham** [comment]
@KaydeeDee / @jhutchings1 Please could one of you triage this ticket? it has incorrectly been marked as resolved. At this moment in time. openTofu and any version of terraform below 1.11 is broken

**Comment by jhutchings1** [comment]
Hey folks, we missed one of the WriteOnly statements in 5.7 which was intended to fix this. @GreenStage, you fixed that one already, right? I don't have a linked issue from this particular one. cc: @musa-cf

**Comment by GreenStage** [comment]
No, there was no open issue.
Added an internal issue tracking and fixing it here: https://github.com/cloudflare/terraform-provider-cloudflare/pull/5816

**Comment by jimmyjones2** [comment]
@jhutchings1 I've not tested v5.8.0 yet, but looks as if another WriteOnly has snuck in - maybe need some tests to prevent this reoccurring?

https://github.com/cloudflare/terraform-provider-cloudflare/commit/409e81bb9fd745ee48f4e07c98eb61fd9879c3b5

**Comment by KaydeeDee** [comment]
Hi there - with @GreenStage 's fix, this should be resolved. Are you seeing this in 5.10+?

**Comment by jimmyjones2** [comment]
This is now fixed for me, thanks!

**Comment by drewmullen** [comment]
I think the issue here is more to do with the implementation. Ephemeral documentation recommends having both a write-only and non-write-only field for backwards compatibility reasons. This [feature](https://github.com/cloudflare/terraform-provider-cloudflare/pull/5816) merely flipped the existing argument to write-only.

Here is a blog post I wrote with guidance on how to implement: https://dev.to/drewmullen/writing-terraform-resources-with-write-only-parameters-570j
