### ISSUE TITLE
`cloudflare_dns_records` is always updated in-place

### ISSUE THREAD

**Issue by deansheather** [cloudflare/terraform-provider-cloudflare#5858]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.12.2
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v5.8.2

### Affected resource(s)

- cloudflare_dns_record

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.8"
    }
  }
}

provider "cloudflare" {}

resource "cloudflare_dns_record" "test" {
  zone_id = "[redacted]"
  name    = "deantest.coder.com"
  type    = "CNAME"
  content = "dev.coder.com"
  ttl     = 1
  proxied = false
  comment = "Test record"
  settings = {
    flatten_cname = false
    ipv4_only     = false
    ipv6_only     = false
  }
}
```

### Link to debug output

https://gist.github.com/deansheather/34191d5e95c83247d5887ea6bbd1b43d

### Expected output

No updates performed when no properties have changed in the config or outside of Terraform.

### Actual output

Detects changes on `settings`, which causes the resource to be updated in-place.

### Steps to reproduce

```
$ terraform init
$ terraform plan -out=plan.tfplan
$ terraform apply plan.tfplan
$ terraform plan
# cloudflare_dns_record.test will be updated in-place
```

### Additional factoids

To work around this for now, I'm ignoring changes from `settings`.

Tested with `A` records too, it seems to always detect changes on `settings`.

### References

This issue is closed but it seems like a very similar bug: https://github.com/cloudflare/terraform-provider-cloudflare/issues/5517

**Comment by dsiguero** [comment]
Still happening in 5.8.2.. how they managed to release something so broken?

This comment fixed it: https://github.com/cloudflare/terraform-provider-cloudflare/issues/5517#issuecomment-2917715192

**Comment by sprat** [comment]
@dsiguero The OP used fully qualified names in their record but still have a problem. But, it's strange, I have absolutely no issue with my CNAME records after qualifying the record names.

However, all my SRV records are still broken after the name change, so I suspect that changing the record name is not enough to fully fix the issue.

**Comment by sprat** [comment]
I've debugged the problem, and for DNS SRV records I had to perform this change:
```
resource "cloudflare_dns_record" "imap" {
  zone_id  = cloudflare_zone.this.id
  name     = "_imaps._tcp.${cloudflare_zone.this.name}"
  type     = "SRV"
  ttl      = 1
  data = {
    priority = 0
    weight   = 0
    port     = 993
    target   = "mail.infomaniak.com"
  }
}
```
becomes:
```
resource "cloudflare_dns_record" "imap" {
  zone_id  = cloudflare_zone.this.id
  name     = "_imaps._tcp.${cloudflare_zone.this.name}"
  type     = "SRV"
  ttl      = 1
  priority = 0
  data = {
    priority = 0
    weight   = 0
    port     = 993
    target   = "mail.infomaniak.com"
  }
}
```
The priority field should be specified at 2 different places... I would qualify this as a bug.

**Comment by deansheather** [comment]
It seems like a recurring pattern that many fields in this provider generate drift, either always or when the API silently mutates the field.

**Comment by KaydeeDee** [comment]
Hey all - I see this issue has come back up/is persistent. I've let the team working on DNS know so that they can investigate.

**Comment by ghost** [comment]
Hi,

There seem to be two unrelated issues here. I'll try my best to address both of them:

- @deansheather, do you need `ipv4_only` and `ipv6_only` to be listed explicitly? The API hides these settings when `false`, so, as unfortunate as it is that we likely (though I'll double-check with the responsible team) can't silently tolerate diffs like that, I believe this is expected behavior. In my testing, omitting `ipv4_only` and `ipv6_only` gets rid of the diff.
- @sprat, this isn't as much of an issue with the Terraform provider as it is an unfortunate historical behavior of our API. The good news is that we plan to remove the priority field outside of the data map entirely, which will eliminate this issue. The bad news is that this is a breaking API change and will take quite a while to complete.

**Comment by deansheather** [comment]
> can't silently tolerate diffs like that, I believe this is expected behavior.

Well, if that's the case the provider should be updated to consider those fields as false when they're not provided by the API.

My use case is allowing everyone at the company the ability to add their record (with all fields, including `ipv4_only` and `ipv6_only`) to a terraform variable and all of the records to be created from that.

**Comment by deansheather** [comment]
Another field that has issues very similar to this is `tags`, which seems to be sorted by the server on responses, and always generates drift. Maybe the provider should require the input to be always sorted? Or treat it like a set and don't care about ordering when assessing drift

**Comment by deansheather** [comment]
> this isn't as much of an issue with the Terraform provider as it is an unfortunate historical behavior of our API.

This is 100% an issue with your provider. The provider should be working around these limitations in your API, otherwise the provider suffers from death from a thousand cuts.

Part of the Terraform contract is that a second apply without changes should be a no-op. It's extremely annoying when you do a Terraform plan and it can't give you a straight answer on what has actually changed. Your unit tests do not seem to be comprehensive enough, or do not catch post-apply plan not being empty.

At my company we've written multiple Terraform providers for our own product, and while it sucks that our API has a few limitations that require clever workarounds, we were able to create a provider that doesn't drift every time you apply.

From what I can tell, fields that cause drift are:
- `name = "@"` gets updated to the full zone name on the API, the provider doesn't reject `@`
- `name = "subdomain-only"` gets updated to the full record name on the API, the provider doesn't reject partial names
- `name = "UpperCase.zone.com"` gets updated to lowercase on the API, the provider doesn't reject uppercase
- `settings.ipv[4|6]_only = false` doesn't get returned by the API, only returned when true
- `tags` gets sorted by the API, and the provider doesn't ignore/reject unsorted input (or use a set)
- `priority` and `data.priority` need to contain the same value, as they are populated from the same API field

And this is just the `cloudflare_dns_record` resource! I imagine most other resources in your provider have similar issues.

**Comment by sprat** [comment]
I agree with @deansheather: as users we expect that there's no drift detection when nothing has changed in the resources definitions. I understand that there are technical difficulties to fully generate a provider from an API definition only, but IMO you should make sure that either your API don't accept things it previously accepted (e.g. @ or short-form DNS names) or don't flag "internal transformations" as drifts in the provider.

**Comment by ghost** [comment]
I understand, and I agree that there are usability improvements to be made, but for now we need to work with the tools that are available to us. Our Terraform folks are hard at work improving the provider and allowing individual API service teams to describe their schemas more expressively, which will then allow for better provider code to be generated. This isn't me dismissing the issues—just saying it's expected to take some time to polish everything.

- `name` — discussed extensively in #5517, this is probably the trickiest issue. Domain name normalization rules are complex (especially when Punycode is added to the mix) and I don't think we'd want that code in the provider. It's more likely we'll move in the direction of rejecting short names, but my comment on #5517 elaborates more on that. Names with Unicode characters not encoded as Punycode would still show diffs, as they did in provider v4. Like I wrote in #5517, if using full domain names isn't possible for any reason, we'd love to hear about it.
- `ipv4_only` and `ipv6_only` — we're hopefully somewhat close to getting a way to deal with this. Regardless, these are obscure settings that are (luckily) almost never used, and that for the longest time weren't even customer-controllable. For now, I think omitting them is an acceptable work-around. Provider v4 didn't support them at all. That said, we hope to get a way to deal with this in the coming weeks or months.
- `tags` — we have a way to deal with this and a future provider update in the coming weeks should hide any diffs related to tag ordering.
- `priority` — this will be dealt with on the API level so that all users of the API can benefit from it.

This issue was originally about `ipv4_only` and `ipv6_only`. Please open a new issue if you run into any other problems. Note, however, that our API normalizes lots of data, and much of that is specific to certain record types. For example, try creating a `TXT` record with content `"many"     spaces`. **Not all diffs related to data normalization are automatically considered bugs**, otherwise we'd have to add a full DNS normalization library to the provider. That said, we hear your feedback, we've passed it on, and we'll continue to work to improve our schema and eliminate unnecessary diffs as tools for it become available. Please be patient and bear with us!

_(Internal tracking references: DNS-10445, DNS-12087, DNS-12206, DNS-12211, DNS-12212.)_

**Comment by KaydeeDee** [comment]
Thank you @janik-cloudflare - I'm going to mark this issue as closed for now.

As mentioned, the team is focused on improving v5 right now and we are releasing every two weeks to get these improvements and stabilization out to you. This is their top priority - we do hear you and we're working as quickly as possible across all resources.

**Comment by adityapatadia** [comment]
I can't believe Cloudflare shipped it and is still not able to resolve this after months. Sheet disappointment..

**Comment by javgo** [comment]
Hi. Do we have a resolution for this? I'm experiencing this issue with the latest released provider (5.8.4). Thanks!

**Comment by ghost** [comment]
@javgo, are you perhaps passing in an incomplete record name such as "www" that's being normalized to "www.example.com"? If that's not it, please have a look at my latest comment to see if any of the other notes apply, and if those don't either, please provide steps to reproduce.

**Comment by javgo** [comment]
Hi @janik-cloudflare Thanks for you message. I'll copy an snippet of our code to see if it's any help

Terraform version: `1.11.4`
Cloudflare provider version: `5.8.4`

One of the multiple dns records that the terraform plan is trying to permanently modify:

```
module "webmail" {
  resource_type = "cloudflare_dns_record"
  source        = "../../../../modules/domain-dns-management/"
  zone_name     = "acme.com"

  record_name = "webmail"
  record_type = "A"

  record_content = ["170.000.000.000"]
}
```
```
/* Cloudflare: DNS Record */
resource "cloudflare_dns_record" "record" {

  #Resource Type: cloudflare_dns_record
  count = (var.resource_type == "cloudflare_dns_record") ? 1 : 0

  zone_id  = local.cloudflare_zones[var.zone_name] #Cloudflare requires the zone id
  name     = var.record_name
  content  = join(",", var.record_content) # Cloudflare does not support lists but strings
  type     = var.record_type
  priority = (contains(["MX"], var.record_type)) ? var.record_priority : 0

  proxied = (contains(["A", "AAAA", "CNAME"], var.record_type)) ? var.record_proxied : false
  ttl     = (var.record_proxied && contains(["A", "AAAA", "CNAME"], var.record_type)) ? 1 : var.record_ttl

  # I tried this to hack the provider into ignoring changes
  lifecycle {
    ignore_changes = [
      data,
      comment_modified_on,
      meta,
      proxiable,
      settings,
      tags,
      tags_modified_on
    ]
  }
}
```


The terraform plan wants to keep changing the resource
```
  # module.dns.module.acme_com.module.webmail.cloudflare_dns_record.record[0] will be updated in-place
  ~ resource "cloudflare_dns_record" "record" {
      + comment_modified_on = (known after apply)
      ~ created_on          = "2025-08-25T12:38:26Z" -> (known after apply)
        id                  = "1d927d0603ca2955be57xxxxxxxxx"
      ~ modified_on         = "2025-08-25T12:38:26Z" -> (known after apply)
      ~ name                = "webmail.acme.com" -> "webmail"
      + priority            = 0
      ~ settings            = {
          + flatten_cname = (known after apply)
          + ipv4_only     = (known after apply)
          + ipv6_only     = (known after apply)
        }
        tags                = []
      + tags_modified_on    = (known after apply)
        # (7 unchanged attributes hidden)
    }
```

I tried removing the dns record from both Cloudflare and the terraform state and re-create it again. Then the issue with the changes reappears, so it seems an issue with the provider and not a faulty state

i also tried setting the `name` attribute to `webmail.acme.com` instead of `webmail` which sorts the name issue, but still it is constantly trying to modify `tags_modified_on`, `created_on`, `modified_on`, `priority` and `settings`

**Comment by ghost** [comment]
Hi @javgo, thanks for the detailed reply! I think `priority` is the culprit here; changing the `0` to `null` seems to fix it in my testing (since `A` records don't have priorities at all, which is different from them having priority zero). Any chance you could give that a try and let me know if it worked? :)

It's a little annoying that all the other fields are appearing in the diff, making it seem like there are more issues. I believe that's something that's being looked into!

**Comment by javgo** [comment]
Hi @janik-cloudflare I've updated my code to set `priority = null` but the drift still occurs for other attributes

```
  # module.dns.module.acme_com.module.webmail.cloudflare_dns_record.record[0] will be updated in-place
  ~ resource "cloudflare_dns_record" "record" {
      + comment_modified_on = (known after apply)
      ~ created_on          = "2025-08-25T12:38:26Z" -> (known after apply)
        id                  = "1d927d0603ca2955be57bc1e2241ca8c"
      ~ modified_on         = "2025-08-25T12:38:26Z" -> (known after apply)
      ~ name                = "webmail.acme.com" -> "webmail"
      ~ settings            = {
          + flatten_cname = (known after apply)
          + ipv4_only     = (known after apply)
          + ipv6_only     = (known after apply)
        }
        tags                = []
      + tags_modified_on    = (known after apply)
        # (7 unchanged attributes hidden)
    }
```

Any ideas? Based on previous comments I believe I'm not the only one experiencing these issues

**Comment by ghost** [comment]
@javgo, the `name` seems to be the issue now, could you make sure that's set to the full name including the zone name?

My general rule is to ignore everything with `(known after apply)` and what remains is the real diff that needs to be fixed.

**Comment by javgo** [comment]
Hi @janik-cloudflare You're right. Forcing the name to be `webmail.acme.com` instead of `webmail` and the `priority = null` is making the drift go away. Is this going to be the standard behaviour from now on? It means that for every DNS record with name attribute `example` now the name has to be `example.acme.com`

Thanks for your help!

**Comment by ghost** [comment]
I'm afraid so @javgo, at least for now. We're looking into it because we'd like to get rid of most common cases of drift like that, but the short form has some weird ambiguous edge-cases (and the Terraform provider isn't directly aware of zone names) so it's possible we'll instead move in the direction of rejecting short names in the API.

**Comment by air3ijai** [comment]
Bellow is a working example and main point are following
- set not defined values to `null` or specific default
- set record based on if it is a root or not
  `v.name == "@" ? merge(v, { name = v.domain }) : merge(v, { name = "${v.name}.${v.domain}"`
- we have to add quotes for `TXT` records

```terraform
# Records
locals {
  records = [
    { domain = "domain.tld", type = "A",     name = "@",    content = "2.2.2.2",         proxied = true,         comment = "A record"},
    { domain = "domain.tld", type = "CNAME", name = "test", content = "org.github.io",   proxied = false,        comment = "CNAME record"},
    { domain = "domain.tld", type = "MX",    name = "@",    content = "smtp.google.com", priority = 1,           comment = "MX record"},
    { domain = "domain.tld", type = "TXT",   name = "@",    content = "\"v=spf1 include:_spf.google.com ~all\"", comment = "TXT record" }
    ]
}

# Zones
data "cloudflare_zones" "active" {
  status = "active"
}

# Zone name to id
locals {
  zones = {
    for zone in data.cloudflare_zones.active.result :
    zone.name => zone.id
  }
}

# DNS records
resource "cloudflare_dns_record" "dns_records" {
  for_each = { for k, v in local.records : "${v.name}.${v.domain} -> ${v.content}" => (
    v.name == "@" ? merge(v, { name = v.domain }) : merge(v, { name = "${v.name}.${v.domain}" })
  ) }

  zone_id  = lookup(local.zones, each.value.domain)
  name     = lookup(each.value, "name", "@")
  content  = lookup(each.value, "content", null)
  priority = lookup(each.value, "priority", null)
  type     = lookup(each.value, "type", "CNAME")
  ttl      = lookup(each.value, "ttl", 1)
  proxied  = lookup(each.value, "proxied", false)
  comment  = try(coalesce("${lookup(each.value, "comment", null)} - Terraform"), "Terraform")
}
```
