### ISSUE TITLE
cloudflare_load_balancer_pool keeps being changed

### ISSUE THREAD

**Issue by darkweaver87** [cloudflare/terraform-provider-cloudflare#6140]
### Confirmation

- [x] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [x] I have searched the issue tracker and my issue isn't already found.
- [x] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.13.0
Cloudflare v5.9.0

### Affected resource(s)

cloudflare_load_balancer_pool

### Terraform configuration files

```hcl
resource "cloudflare_load_balancer_pool" "xxx" {
  account_id = data.cloudflare_accounts.xxx.result[0].id

  name = "cluster"

  monitor = cloudflare_load_balancer_monitor.tcp_443.id

  origins = [
    {
      name    = "clusterB"
      address = "x.x.x.y"
      weight  = 0
      enabled = true
    },
    {
      name    = "clusterA"
      address = "x.x.x.x"
      weight  = 1
      enabled = true
  }]
}
```

### Link to debug output

you don't need it :-)

### Expected output

Runs should be consistent.

### Actual output

`origins` list keeps being updated.

### Steps to reproduce

1. create a `cloudflare_load_balancer_pool` with 2 origins
2. order origins items descending
3. apply
4. run a `terraform plan`

### Additional factoids

This bugs only happens when origins items are not ordered by name ascending.
The diff should be done on name ordered lists.

**Comment by TyranVdMerwePaytec** [comment]
It keeps changing even when there is a single origin too.

**Comment by TyranVdMerwePaytec** [comment]
The issue seems to be caused by the API omitting properties from the response.

**Examples:**

- disabled_at
- load_shedding, load_shedding.default_percent, load_shedding.session_percent
- notification_filter.origin.disable
- notification_filter.pool.disable
-  origins[].disabled_at (when enabled), origins[].port (when set to 0),

**Comment by rrabelloo** [comment]
Same here!
I've tested many resources combinations including/excluding default values.

Tested with:
- Terraform 1.13.0 / 1.13.1
- Terragrut 0.87.0 / 0.86.2
- Cloudflare provider 5.10.1 / 5.9.0 / 5.8.4

<details>
<summary>Plan output</summary>

```
# cloudflare_load_balancer_pool.pools["lb-pool-test"] will be updated in-place
~ resource "cloudflare_load_balancer_pool" "test" {
    + disabled_at         = (known after apply)
      id                  = "<REDACTED>"
    + load_shedding       = (known after apply)
    ~ modified_on         = "2025-09-15T06:47:14.339529Z" -> (known after apply)
      name                = "lb-pool-test"
    ~ networks            = [
        - "cloudflare",
      ] -> (known after apply)
    ~ notification_email  = null -> (known after apply)
    ~ notification_filter = {
        + origin = (known after apply)
        ~ pool   = {
            + disable = false
          }
      }
    ~ origins             = [
        ~ {
            + disabled_at = (known after apply)
              name        = "origin-1"
              # (4 unchanged attributes hidden)
          },
      ]
      # (8 unchanged attributes hidden)
  }
```

</details>

**Comment by KaydeeDee** [comment]
Hi there - I've created a ticket for the team to look into. Thank you for submitting an issue!

**Comment by randy-coburn-zeam** [comment]
Any feedback on this? It's still an active issue with the provider.

**Comment by lewwcom** [comment]
I believe that the problem lies in the `notification_filter` attribute.

Let's say `notification_filter.pool` is not in your state, If you specify `notification_filter.pool` that matches the default value

```hcl
# Either
notification_filter = {
  pool = {}
}

# Or
notification_filter = {
  pool = {
    disable = false # Default value of `disable`
  }
}
```

`tofu plan`, for **BOTH** configuration in the example above, will report the change

```hcl
     + notification_filter = {
           + origin = (known after apply)
           + pool   = {
               + disable = false
             }
         }
```

After `⁠tofu apply`, you would expect the state to reflect the configuration applied to Cloudflare. However, this is not the case. A subsequent `plan -refresh-only` reveals a drift:

```plaintext
$ tofu plan -target cloudflare_load_balancer_pool.<masked> -refresh-only

cloudflare_load_balancer_monitor.<masked>: Refreshing state... [id=<masked>]
cloudflare_load_balancer_pool.<masked>: Refreshing state... [id=<masked>]

Note: Objects have changed outside of OpenTofu

OpenTofu detected the following changes made outside of OpenTofu since the last "tofu apply" which may have affected this plan:

   # cloudflare_load_balancer_pool.nginx_ha_fci has changed
   ~ resource "cloudflare_load_balancer_pool" "<masked>" {
         id                  = "<masked>"
         name                = "<masked>"
       ~ notification_filter = {
           ~ pool = {
               - disable = false -> null
             }
         }
         # (12 unchanged attributes hidden)
     }
```

The root cause of this drift is a mismatch between Cloudflare API and Terraform provider behaviours. The table below shows what you get from Cloudflare API and what stored in Terraform state after you `tofu apply` your Terraform configuration.

| `.tf` file                                         | Cloudflare API                        | Terraform state                                    |
| -------------------------------------------------- | ------------------------------------- | -------------------------------------------------- |
| `notification_filter = {pool = {disable = false}}` | `"notification_filter": {"pool": {}}` | `notification_filter = {pool = {disable = false}}` |
| `notification_filter = {pool = {}}`                 | `"notification_filter": {"pool": {}}` | `notification_filter = {pool = {disable = false}}` |

So, when the desired `⁠notification_filter` configuration is equivalent to the default, use:

```hcl
notification_filter = {}   # => `"notification_filter": {}` on Cloudflare

# Or
notification_filter = null # => no `notification_filter` property on Cloudflare
```

I also have doubts about the practical use of the ⁠`notification_filter` property. There doesn't appear to be any corresponding configuration option or button for it within the Cloudflare Dashboard's pool edit page. Also, the "Set up alerts" section on the [Cloudflare 'Create Pool' page](https://developers.cloudflare.com/load-balancing/pools/create-pool/#set-up-alerts) directs users to Cloudflare's centralized notification service, which suggests a different mechanism for managing notifications. So it's possible that ⁠`notification_filter` might be an outdated or unused attribute that should be deprecated or removed.

**Comment by dmx-on** [comment]
Hi. Can you please fix this bug? I am waiting for an year for this bug to be fixed...

I am using the newest provider `5.18.0` and still in upgrade loop:

```shell
# cloudflare_load_balancer_pool.pool["test-lb:ingress-aks-test"] will be updated in-place
~ resource "cloudflare_load_balancer_pool" "pool" {
    + disabled_at        = (known after apply)
      id                 = "****"
    ~ modified_on        = "2026-03-06T09:27:09.708834Z" -> (known after apply)
      name               = "ingress-aks-test"
    ~ networks           = [
        - "cloudflare",
      ] -> (known after apply)
    ~ origins            = [
        ~ {
            + disabled_at = (known after apply)
              name        = "ingress-aks-replica.****"
            + port        = 0
              # (3 unchanged attributes hidden)
          },
        ~ {
            + disabled_at = (known after apply)
              name        = "ingress-aks.****"
            + port        = 0
              # (3 unchanged attributes hidden)
          },
      ]
      # (7 unchanged attributes hidden)
  }
```

**Comment by ValeriiVozniuk** [comment]
Same issue here, and the same output as for dmx-on above, always want to change networks part, despite it is not defined in config
```
      ~ networks           = [
          - "cloudflare",
        ] -> (known after apply)

```
and add port=0, despite it is explicitly set in origins
```
            + port        = 0
```

**Comment by KaydeeDee** [comment]
this issue is resolved!

**Comment by dmx-on** [comment]
Hi @KaydeeDee . What provider version suppose to get this change because `5.19.0` still generates the same upgrade loop?

**Comment by ValeriiVozniuk** [comment]
Not fixed in 5.19.1

**Comment by dmx-on** [comment]
Hi @KaydeeDee is there any news on this?

**Comment by bahag-klickst** [comment]
@KaydeeDee 
This issue is not resolved, we are facing the same issue with v5.19.1

**Comment by dmx-on** [comment]
The bug is still present in version `5.20.0`

**Comment by joeltheiconic** [comment]
This bug is still present in `5.21.1` @KaydeeDee

**Comment by krokwen-tftc** [comment]
`networks` is suppressed if set to `null` (anyway it's a r/o parameter)
and also there is a change highligthed in `load_shedding`
i have
```
  load_shedding = {
    default_policy = "random"
    session_policy = "hash"
  }
```
and it highlights
```
  load_shedding = {
+    default_percent = 0
+    session_percent = 0
  }
```
every time, no matter what i do. ignore_changes doesn't work -__-

provider version 5.23.0
