### ISSUE TITLE
Can't import an `origin_ca_certificate` that was auto created in the UI and get the state happy

### ISSUE THREAD

**Issue by spkane** [cloudflare/terraform-provider-cloudflare#950]
### Terraform version

Terraform v0.14.6
+ provider registry.terraform.io/cloudflare/cloudflare v2.18.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0

### Affected resource(s)

cloudflare_origin_ca_certificate

### Terraform configuration files

```hcl
resource "cloudflare_origin_ca_certificate" "examplecom" {
  csr                = tls_cert_request.example.cert_request_pem
  hostnames          = [ "*.example.com", "example.com" ]
  request_type       = "origin-rsa"
}
```

### Debug output

* Passing in a new CSR
```
  # cloudflare_origin_ca_certificate.examplecom must be replaced
-/+ resource "cloudflare_origin_ca_certificate" "example.com" {
      ~ certificate  = <<-EOT
            -----BEGIN CERTIFICATE-----
            -----END CERTIFICATE-----
        EOT -> (known after apply)
      + csr          = (known after apply) # forces replacement
      ~ expires_on   = "2035-09-22T16:59:00Z" -> (known after apply)
      ~ id           = "175209660213919493265962486908716583606690994541" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

* Passing in an empty string for the CSR
```
Error: "csr": invalid PEM data

  on example.tf line 31, in resource "cloudflare_origin_ca_certificate" "examplecom":
  31: resource "cloudflare_origin_ca_certificate" "examplecom" {
```

* Passing in null for the CSR (which matches what is in the state after an import)
```
Error: "csr": required field is not set

  on examplecom.tf line 31, in resource "cloudflare_origin_ca_certificate" "examplecom":
  31: resource "cloudflare_origin_ca_certificate" "examplecom" {
```

### Panic output

N/A

### Expected behavior

* I think that you should be able to set the CSR to `null` for this use-case, since the API does not return the CSR during the import from what I can tell.

### Actual behavior

* Terraform either complains that the CSR is required, wants to recreate the certificate if you provide it with a new CSR, or complains about the CSR data if you provide it with something like an empty string.

### Steps to reproduce

* Create an Origin CA Certificate through the UI
* Import that Origin CA Certificate into terraform
* Try to do a `terraform plan` and get a no-op back.

### Important factoids

* This is specifically focused on trying to import an existing Origin CA cert that was created via the Cloudflare UI.

### References

N/A

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
I don't _think_ this is a bug as it is similar to how other TLS certificates work where the sensitive material isn't ever exposed via the API and any updates actually trigger a new resource internally so the Terraform lifecycle matches that. With the other TLS certificate resources, the position is to either manage it in the UI or in Terraform (completely, not just importing) so that you have all the resources managed fully.

**Comment by spkane** [comment]
@jacobbednarz So, a feature request? (I understand where you are coming from, but I think the request is still reasonable and valid)

I get that I can't get the CSR from the API, but I can import the certificate and if someone would like to do that, it would be nice if the provider was OK with that. I suppose I might be able to use `lifecycle` rules to fake it, by providing `valid` CSR PEM data, and just telling terraform to ignore the change/mis-match, but that seems like it would be more confusing to someone looking at the code later, where-as `null` is obviously not a valid CSR, but does map to what the API returns in the case of an import and is therefor a valid state that can be documenting as only being valid for imported certs. Since as a cloudflare user I have the certificate, but I do not have the CSR.

For new sites/domain I will fully manage it via terraform, but I would STRONGLY prefer to be able to import the existing site certificates without being forced to either ignore them, or immediately rotate/recreate them.

**Comment by jacobbednarz** [comment]
> I get that I can't get the CSR from the API, but I can import the certificate and if someone would like to do that, it would be nice if the provider was OK with that.

From the providers perspective, the CSR is changing from what it has knowledge of and doesn't have a way of syncing the configuration, state and remote API into a uniform representation -- hence part of the requirement for `ForceNew` on the attribute. Without this, it is possible that one of those three get out of sync and there is no loger a way to automatically bring them back into alignment (which is the goal of tools like Terraform). 

The approach you're taking isn't what I'd put under the "happy path" of managing configuration as you've got resources which can't be fully managed under Terraform in their current state (due to constraints like the lack of in-place updates) but you're attempting to. The only way you could achieve this is by manual intervention and editing the Terraform state yourself which is possible but be sure to take the nessecary precautions as a bad config is hard to recover from 😄 This isn't something we can do in the provider itself so the onus falls to the end user.

One thing we haven't really touched on is _why_ the CSR attribute is missing from the API responses. It's [documented](https://api.cloudflare.com/#origin-ca-properties) as being returned in the GET requests 🤔 Let me chase this up internally as that might be the solution here instead of changing the schema.

**Comment by spkane** [comment]
Thank you. I hear what you are saying and do general agree. I was just mostly hoping for a middle ground until we get to a point that we can recreate the cert in question.

I am glad to hear that the CSR "should" be returned though. I have never considered them secret myself, so I was a bit surprised that it wasn't imported initially, but didn't dig into the API docs about it.

Interested to hear what you find out. Thanks!

**Comment by jacobbednarz** [comment]
I've managed to rummage through some history for this and the reason this field was initially made `Required` isn't applicable anymore and we can make it `Optional` and move some of the checks into the `Create` method itself.

Thanks for the great discussion @spkane -- I'll take a look at updating this shortly.

**Comment by jacobbednarz** [comment]
I've opened #955 to address this. Would you mind pulling it locally, building and confirming it matches your use case? Along with this, I also uncovered another bug in this resource (related to persisting `requested_validity`) which should also be fixed with the next release.

**Comment by spkane** [comment]
Sure. I'll give it a try and let you know what I see.

**Comment by LanceSandino** [comment]
I still have this problem when importing or trying to create

```
 Error: error creating origin certificate: HTTP status 400: CSR parsed as empty (1007)
│
│   with cloudflare_origin_ca_certificate.example,
│   on cloudflare-ca.tf line 1, in resource "cloudflare_origin_ca_certificate" "example":
│    1: resource "cloudflare_origin_ca_certificate" "example" {
│
```
